// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package evm

import (
	"errors"

	"google.golang.org/protobuf/types/known/anypb"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2"
	sdkpb "github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2/pb"
)

type EVMChain struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *EVMChain) CallContract(runtime sdk.DonRuntime, input *CallContractRequest) sdk.Promise[*CallContractReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*CallContractReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "CallContract",
	}), func(i *sdkpb.CapabilityResponse) (*CallContractReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &CallContractReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) FilterLogs(runtime sdk.DonRuntime, input *FilterLogsRequest) sdk.Promise[*FilterLogsReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*FilterLogsReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "FilterLogs",
	}), func(i *sdkpb.CapabilityResponse) (*FilterLogsReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &FilterLogsReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) BalanceAt(runtime sdk.DonRuntime, input *BalanceAtRequest) sdk.Promise[*BalanceAtReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*BalanceAtReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "BalanceAt",
	}), func(i *sdkpb.CapabilityResponse) (*BalanceAtReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &BalanceAtReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) EstimateGas(runtime sdk.DonRuntime, input *EstimateGasRequest) sdk.Promise[*EstimateGasReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*EstimateGasReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "EstimateGas",
	}), func(i *sdkpb.CapabilityResponse) (*EstimateGasReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &EstimateGasReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) GetTransactionByHash(runtime sdk.DonRuntime, input *TransactionByHashRequest) sdk.Promise[*TransactionByHashReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*TransactionByHashReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "GetTransactionByHash",
	}), func(i *sdkpb.CapabilityResponse) (*TransactionByHashReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &TransactionByHashReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) GetTransactionReceipt(runtime sdk.DonRuntime, input *TransactionReceiptRequest) sdk.Promise[*TransactionReceiptReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*TransactionReceiptReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "GetTransactionReceipt",
	}), func(i *sdkpb.CapabilityResponse) (*TransactionReceiptReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &TransactionReceiptReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) LatestAndFinalizedHead(runtime sdk.DonRuntime, input *emptypb.Empty) sdk.Promise[*LatestAndFinalizedHeadReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*LatestAndFinalizedHeadReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "LatestAndFinalizedHead",
	}), func(i *sdkpb.CapabilityResponse) (*LatestAndFinalizedHeadReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &LatestAndFinalizedHeadReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) QueryTrackedLogs(runtime sdk.DonRuntime, input *QueryTrackedLogsRequest) sdk.Promise[*QueryTrackedLogsReply] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*QueryTrackedLogsReply](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "QueryTrackedLogs",
	}), func(i *sdkpb.CapabilityResponse) (*QueryTrackedLogsReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &QueryTrackedLogsReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) RegisterLogTracking(runtime sdk.DonRuntime, input *RegisterLogTrackingRequest) sdk.Promise[*emptypb.Empty] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*emptypb.Empty](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "RegisterLogTracking",
	}), func(i *sdkpb.CapabilityResponse) (*emptypb.Empty, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &emptypb.Empty{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}

func (c *EVMChain) UnregisterLogTracking(runtime sdk.DonRuntime, input *UnregisterLogTrackingRequest) sdk.Promise[*emptypb.Empty] {
	wrapped, err := anypb.New(input)
	if err != nil {
		return sdk.PromiseFromResult[*emptypb.Empty](nil, err)
	}
	return sdk.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "mainnet-evm@1.0.0",
		Payload: wrapped,
		Method:  "UnregisterLogTracking",
	}), func(i *sdkpb.CapabilityResponse) (*emptypb.Empty, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &emptypb.Empty{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}
