// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: capabilities_registry.proto

package pb

import (
	pb "github.com/smartcontractkit/chainlink-common/pkg/capabilities/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteAPIType int32

const (
	ExecuteAPIType_EXECUTE_API_TYPE_UNKNOWN  ExecuteAPIType = 0
	ExecuteAPIType_EXECUTE_API_TYPE_TRIGGER  ExecuteAPIType = 1
	ExecuteAPIType_EXECUTE_API_TYPE_EXECUTE  ExecuteAPIType = 2
	ExecuteAPIType_EXECUTE_API_TYPE_COMBINED ExecuteAPIType = 3
)

// Enum value maps for ExecuteAPIType.
var (
	ExecuteAPIType_name = map[int32]string{
		0: "EXECUTE_API_TYPE_UNKNOWN",
		1: "EXECUTE_API_TYPE_TRIGGER",
		2: "EXECUTE_API_TYPE_EXECUTE",
		3: "EXECUTE_API_TYPE_COMBINED",
	}
	ExecuteAPIType_value = map[string]int32{
		"EXECUTE_API_TYPE_UNKNOWN":  0,
		"EXECUTE_API_TYPE_TRIGGER":  1,
		"EXECUTE_API_TYPE_EXECUTE":  2,
		"EXECUTE_API_TYPE_COMBINED": 3,
	}
)

func (x ExecuteAPIType) Enum() *ExecuteAPIType {
	p := new(ExecuteAPIType)
	*p = x
	return p
}

func (x ExecuteAPIType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteAPIType) Descriptor() protoreflect.EnumDescriptor {
	return file_capabilities_registry_proto_enumTypes[0].Descriptor()
}

func (ExecuteAPIType) Type() protoreflect.EnumType {
	return &file_capabilities_registry_proto_enumTypes[0]
}

func (x ExecuteAPIType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteAPIType.Descriptor instead.
func (ExecuteAPIType) EnumDescriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{0}
}

// DON has arguments for [github.com/smartcontractkit/chainlink-common/pkg/capabilities.DON].
type DON struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Members       [][]byte               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` // [n][32]byte where n is the number of members
	F             uint32                 `protobuf:"varint,3,opt,name=f,proto3" json:"f,omitempty"`            // uint8
	ConfigVersion uint32                 `protobuf:"varint,4,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Families      []string               `protobuf:"bytes,6,rep,name=families,proto3" json:"families,omitempty"` // [n]string where n is the number of DON families
	Config        []byte                 `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DON) Reset() {
	*x = DON{}
	mi := &file_capabilities_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DON) ProtoMessage() {}

func (x *DON) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DON.ProtoReflect.Descriptor instead.
func (*DON) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{0}
}

func (x *DON) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DON) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *DON) GetF() uint32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *DON) GetConfigVersion() uint32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *DON) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DON) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *DON) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // [32]byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRequest) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

// LocalNode has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.LocalNode].
type NodeReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PeerID              []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // [32]byte
	WorkflowDON         *DON                   `protobuf:"bytes,2,opt,name=workflowDON,proto3" json:"workflowDON,omitempty"`
	CapabilityDONs      []*DON                 `protobuf:"bytes,3,rep,name=CapabilityDONs,proto3" json:"CapabilityDONs,omitempty"`
	NodeOperatorID      uint32                 `protobuf:"varint,4,opt,name=nodeOperatorID,proto3" json:"nodeOperatorID,omitempty"`          // uint32
	Signer              []byte                 `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`                           // [32]byte
	EncryptionPublicKey []byte                 `protobuf:"bytes,6,opt,name=encryptionPublicKey,proto3" json:"encryptionPublicKey,omitempty"` // [32]byte
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeReply) Reset() {
	*x = NodeReply{}
	mi := &file_capabilities_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReply) ProtoMessage() {}

func (x *NodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReply.ProtoReflect.Descriptor instead.
func (*NodeReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{2}
}

func (x *NodeReply) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

func (x *NodeReply) GetWorkflowDON() *DON {
	if x != nil {
		return x.WorkflowDON
	}
	return nil
}

func (x *NodeReply) GetCapabilityDONs() []*DON {
	if x != nil {
		return x.CapabilityDONs
	}
	return nil
}

func (x *NodeReply) GetNodeOperatorID() uint32 {
	if x != nil {
		return x.NodeOperatorID
	}
	return 0
}

func (x *NodeReply) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *NodeReply) GetEncryptionPublicKey() []byte {
	if x != nil {
		return x.EncryptionPublicKey
	}
	return nil
}

// Get has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.Get].
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetReply has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.Get], expressed as a capabilityID (this is a GRPC connectionID internal to go-hashicorp-plugin) and type indicating client wrapper that we need to use on the client side.
type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  uint32                 `protobuf:"varint,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	Type          ExecuteAPIType         `protobuf:"varint,2,opt,name=type,proto3,enum=loop.ExecuteAPIType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_capabilities_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetReply) GetCapabilityID() uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return 0
}

func (x *GetReply) GetType() ExecuteAPIType {
	if x != nil {
		return x.Type
	}
	return ExecuteAPIType_EXECUTE_API_TYPE_UNKNOWN
}

// GetTrigger has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.GetTrigger].
type GetTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTriggerRequest) Reset() {
	*x = GetTriggerRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriggerRequest) ProtoMessage() {}

func (x *GetTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriggerRequest.ProtoReflect.Descriptor instead.
func (*GetTriggerRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetTriggerReply has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.GetTrigger], expressed as a capabilityID (this is a GRPC connectionID internal to go-hashicorp-plugin).
type GetTriggerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  uint32                 `protobuf:"varint,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTriggerReply) Reset() {
	*x = GetTriggerReply{}
	mi := &file_capabilities_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTriggerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriggerReply) ProtoMessage() {}

func (x *GetTriggerReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriggerReply.ProtoReflect.Descriptor instead.
func (*GetTriggerReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetTriggerReply) GetCapabilityID() uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return 0
}

// GetExecutableRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.GetExecutable].
type GetExecutableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutableRequest) Reset() {
	*x = GetExecutableRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutableRequest) ProtoMessage() {}

func (x *GetExecutableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutableRequest.ProtoReflect.Descriptor instead.
func (*GetExecutableRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{7}
}

func (x *GetExecutableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetExecutableReply has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.GetExecutable], expressed as a capabilityID (this is a GRPC connectionID internal to go-hashicorp-plugin).
type GetExecutableReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  uint32                 `protobuf:"varint,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutableReply) Reset() {
	*x = GetExecutableReply{}
	mi := &file_capabilities_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutableReply) ProtoMessage() {}

func (x *GetExecutableReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutableReply.ProtoReflect.Descriptor instead.
func (*GetExecutableReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetExecutableReply) GetCapabilityID() uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return 0
}

// ListReply has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.List], expressed as a capabilityID (this is a GRPC connectionID internal to go-hashicorp-plugin).
type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  []uint32               `protobuf:"varint,1,rep,packed,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_capabilities_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ListReply) GetCapabilityID() []uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return nil
}

// GetTargetReply has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.GetTrigger], expressed as a capabilityID (this is a GRPC connectionID internal to go-hashicorp-plugin).
type GetTargetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  uint32                 `protobuf:"varint,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetReply) Reset() {
	*x = GetTargetReply{}
	mi := &file_capabilities_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetReply) ProtoMessage() {}

func (x *GetTargetReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetReply.ProtoReflect.Descriptor instead.
func (*GetTargetReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetTargetReply) GetCapabilityID() uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return 0
}

// Add has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.Add].
type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  uint32                 `protobuf:"varint,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	Type          ExecuteAPIType         `protobuf:"varint,2,opt,name=type,proto3,enum=loop.ExecuteAPIType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{11}
}

func (x *AddRequest) GetCapabilityID() uint32 {
	if x != nil {
		return x.CapabilityID
	}
	return 0
}

func (x *AddRequest) GetType() ExecuteAPIType {
	if x != nil {
		return x.Type
	}
	return ExecuteAPIType_EXECUTE_API_TYPE_UNKNOWN
}

// Remove has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.CapabilitiesRegistry.Remove].
type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigForCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  string                 `protobuf:"bytes,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	DonID         uint32                 `protobuf:"varint,2,opt,name=donID,proto3" json:"donID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigForCapabilityRequest) Reset() {
	*x = ConfigForCapabilityRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigForCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigForCapabilityRequest) ProtoMessage() {}

func (x *ConfigForCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigForCapabilityRequest.ProtoReflect.Descriptor instead.
func (*ConfigForCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigForCapabilityRequest) GetCapabilityID() string {
	if x != nil {
		return x.CapabilityID
	}
	return ""
}

func (x *ConfigForCapabilityRequest) GetDonID() uint32 {
	if x != nil {
		return x.DonID
	}
	return 0
}

type ConfigForCapabilityReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CapabilityConfig *pb.CapabilityConfig   `protobuf:"bytes,1,opt,name=capability_config,json=capabilityConfig,proto3" json:"capability_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigForCapabilityReply) Reset() {
	*x = ConfigForCapabilityReply{}
	mi := &file_capabilities_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigForCapabilityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigForCapabilityReply) ProtoMessage() {}

func (x *ConfigForCapabilityReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigForCapabilityReply.ProtoReflect.Descriptor instead.
func (*ConfigForCapabilityReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigForCapabilityReply) GetCapabilityConfig() *pb.CapabilityConfig {
	if x != nil {
		return x.CapabilityConfig
	}
	return nil
}

type DONForCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityID  string                 `protobuf:"bytes,1,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DONForCapabilityRequest) Reset() {
	*x = DONForCapabilityRequest{}
	mi := &file_capabilities_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DONForCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DONForCapabilityRequest) ProtoMessage() {}

func (x *DONForCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DONForCapabilityRequest.ProtoReflect.Descriptor instead.
func (*DONForCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{15}
}

func (x *DONForCapabilityRequest) GetCapabilityID() string {
	if x != nil {
		return x.CapabilityID
	}
	return ""
}

type DONWithNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Don           *DON                   `protobuf:"bytes,1,opt,name=don,proto3" json:"don,omitempty"`
	Nodes         []*NodeReply           `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DONWithNodes) Reset() {
	*x = DONWithNodes{}
	mi := &file_capabilities_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DONWithNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DONWithNodes) ProtoMessage() {}

func (x *DONWithNodes) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DONWithNodes.ProtoReflect.Descriptor instead.
func (*DONWithNodes) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{16}
}

func (x *DONWithNodes) GetDon() *DON {
	if x != nil {
		return x.Don
	}
	return nil
}

func (x *DONWithNodes) GetNodes() []*NodeReply {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DONForCapabilityReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dons          []*DONWithNodes        `protobuf:"bytes,1,rep,name=dons,proto3" json:"dons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DONForCapabilityReply) Reset() {
	*x = DONForCapabilityReply{}
	mi := &file_capabilities_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DONForCapabilityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DONForCapabilityReply) ProtoMessage() {}

func (x *DONForCapabilityReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DONForCapabilityReply.ProtoReflect.Descriptor instead.
func (*DONForCapabilityReply) Descriptor() ([]byte, []int) {
	return file_capabilities_registry_proto_rawDescGZIP(), []int{17}
}

func (x *DONForCapabilityReply) GetDons() []*DONWithNodes {
	if x != nil {
		return x.Dons
	}
	return nil
}

var File_capabilities_registry_proto protoreflect.FileDescriptor

const file_capabilities_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bcapabilities_registry.proto\x12\x04loop\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ecapabilities/pb/registry.proto\"\xab\x01\n" +
	"\x03DON\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\amembers\x18\x02 \x03(\fR\amembers\x12\f\n" +
	"\x01f\x18\x03 \x01(\rR\x01f\x12$\n" +
	"\rconfigVersion\x18\x04 \x01(\rR\rconfigVersion\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bfamilies\x18\x06 \x03(\tR\bfamilies\x12\x16\n" +
	"\x06config\x18\a \x01(\fR\x06config\"%\n" +
	"\vNodeRequest\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\"\xf5\x01\n" +
	"\tNodeReply\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\x12+\n" +
	"\vworkflowDON\x18\x02 \x01(\v2\t.loop.DONR\vworkflowDON\x121\n" +
	"\x0eCapabilityDONs\x18\x03 \x03(\v2\t.loop.DONR\x0eCapabilityDONs\x12&\n" +
	"\x0enodeOperatorID\x18\x04 \x01(\rR\x0enodeOperatorID\x12\x16\n" +
	"\x06signer\x18\x05 \x01(\fR\x06signer\x120\n" +
	"\x13encryptionPublicKey\x18\x06 \x01(\fR\x13encryptionPublicKey\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\bGetReply\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\rR\fcapabilityID\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.loop.ExecuteAPITypeR\x04type\"#\n" +
	"\x11GetTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetTriggerReply\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\rR\fcapabilityID\"&\n" +
	"\x14GetExecutableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x12GetExecutableReply\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\rR\fcapabilityID\"/\n" +
	"\tListReply\x12\"\n" +
	"\fcapabilityID\x18\x01 \x03(\rR\fcapabilityID\"4\n" +
	"\x0eGetTargetReply\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\rR\fcapabilityID\"Z\n" +
	"\n" +
	"AddRequest\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\rR\fcapabilityID\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.loop.ExecuteAPITypeR\x04type\"\x1f\n" +
	"\rRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x1aConfigForCapabilityRequest\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\tR\fcapabilityID\x12\x14\n" +
	"\x05donID\x18\x02 \x01(\rR\x05donID\"_\n" +
	"\x18ConfigForCapabilityReply\x12C\n" +
	"\x11capability_config\x18\x01 \x01(\v2\x16.loop.CapabilityConfigR\x10capabilityConfig\"=\n" +
	"\x17DONForCapabilityRequest\x12\"\n" +
	"\fcapabilityID\x18\x01 \x01(\tR\fcapabilityID\"R\n" +
	"\fDONWithNodes\x12\x1b\n" +
	"\x03don\x18\x01 \x01(\v2\t.loop.DONR\x03don\x12%\n" +
	"\x05nodes\x18\x02 \x03(\v2\x0f.loop.NodeReplyR\x05nodes\"?\n" +
	"\x15DONForCapabilityReply\x12&\n" +
	"\x04dons\x18\x01 \x03(\v2\x12.loop.DONWithNodesR\x04dons*\x89\x01\n" +
	"\x0eExecuteAPIType\x12\x1c\n" +
	"\x18EXECUTE_API_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18EXECUTE_API_TYPE_TRIGGER\x10\x01\x12\x1c\n" +
	"\x18EXECUTE_API_TYPE_EXECUTE\x10\x02\x12\x1d\n" +
	"\x19EXECUTE_API_TYPE_COMBINED\x10\x032\x85\x05\n" +
	"\x14CapabilitiesRegistry\x126\n" +
	"\tLocalNode\x12\x16.google.protobuf.Empty\x1a\x0f.loop.NodeReply\"\x00\x124\n" +
	"\fNodeByPeerID\x12\x11.loop.NodeRequest\x1a\x0f.loop.NodeReply\"\x00\x12Y\n" +
	"\x13ConfigForCapability\x12 .loop.ConfigForCapabilityRequest\x1a\x1e.loop.ConfigForCapabilityReply\"\x00\x12Q\n" +
	"\x11DONsForCapability\x12\x1d.loop.DONForCapabilityRequest\x1a\x1b.loop.DONForCapabilityReply\"\x00\x12)\n" +
	"\x03Get\x12\x10.loop.GetRequest\x1a\x0e.loop.GetReply\"\x00\x12>\n" +
	"\n" +
	"GetTrigger\x12\x17.loop.GetTriggerRequest\x1a\x15.loop.GetTriggerReply\"\x00\x12G\n" +
	"\rGetExecutable\x12\x1a.loop.GetExecutableRequest\x1a\x18.loop.GetExecutableReply\"\x00\x121\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x0f.loop.ListReply\"\x00\x121\n" +
	"\x03Add\x12\x10.loop.AddRequest\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x06Remove\x12\x13.loop.RemoveRequest\x1a\x16.google.protobuf.Empty\"\x00BCZAgithub.com/smartcontractkit/chainlink-common/pkg/loop/internal/pbb\x06proto3"

var (
	file_capabilities_registry_proto_rawDescOnce sync.Once
	file_capabilities_registry_proto_rawDescData []byte
)

func file_capabilities_registry_proto_rawDescGZIP() []byte {
	file_capabilities_registry_proto_rawDescOnce.Do(func() {
		file_capabilities_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capabilities_registry_proto_rawDesc), len(file_capabilities_registry_proto_rawDesc)))
	})
	return file_capabilities_registry_proto_rawDescData
}

var file_capabilities_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capabilities_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_capabilities_registry_proto_goTypes = []any{
	(ExecuteAPIType)(0),                // 0: loop.ExecuteAPIType
	(*DON)(nil),                        // 1: loop.DON
	(*NodeRequest)(nil),                // 2: loop.NodeRequest
	(*NodeReply)(nil),                  // 3: loop.NodeReply
	(*GetRequest)(nil),                 // 4: loop.GetRequest
	(*GetReply)(nil),                   // 5: loop.GetReply
	(*GetTriggerRequest)(nil),          // 6: loop.GetTriggerRequest
	(*GetTriggerReply)(nil),            // 7: loop.GetTriggerReply
	(*GetExecutableRequest)(nil),       // 8: loop.GetExecutableRequest
	(*GetExecutableReply)(nil),         // 9: loop.GetExecutableReply
	(*ListReply)(nil),                  // 10: loop.ListReply
	(*GetTargetReply)(nil),             // 11: loop.GetTargetReply
	(*AddRequest)(nil),                 // 12: loop.AddRequest
	(*RemoveRequest)(nil),              // 13: loop.RemoveRequest
	(*ConfigForCapabilityRequest)(nil), // 14: loop.ConfigForCapabilityRequest
	(*ConfigForCapabilityReply)(nil),   // 15: loop.ConfigForCapabilityReply
	(*DONForCapabilityRequest)(nil),    // 16: loop.DONForCapabilityRequest
	(*DONWithNodes)(nil),               // 17: loop.DONWithNodes
	(*DONForCapabilityReply)(nil),      // 18: loop.DONForCapabilityReply
	(*pb.CapabilityConfig)(nil),        // 19: loop.CapabilityConfig
	(*emptypb.Empty)(nil),              // 20: google.protobuf.Empty
}
var file_capabilities_registry_proto_depIdxs = []int32{
	1,  // 0: loop.NodeReply.workflowDON:type_name -> loop.DON
	1,  // 1: loop.NodeReply.CapabilityDONs:type_name -> loop.DON
	0,  // 2: loop.GetReply.type:type_name -> loop.ExecuteAPIType
	0,  // 3: loop.AddRequest.type:type_name -> loop.ExecuteAPIType
	19, // 4: loop.ConfigForCapabilityReply.capability_config:type_name -> loop.CapabilityConfig
	1,  // 5: loop.DONWithNodes.don:type_name -> loop.DON
	3,  // 6: loop.DONWithNodes.nodes:type_name -> loop.NodeReply
	17, // 7: loop.DONForCapabilityReply.dons:type_name -> loop.DONWithNodes
	20, // 8: loop.CapabilitiesRegistry.LocalNode:input_type -> google.protobuf.Empty
	2,  // 9: loop.CapabilitiesRegistry.NodeByPeerID:input_type -> loop.NodeRequest
	14, // 10: loop.CapabilitiesRegistry.ConfigForCapability:input_type -> loop.ConfigForCapabilityRequest
	16, // 11: loop.CapabilitiesRegistry.DONsForCapability:input_type -> loop.DONForCapabilityRequest
	4,  // 12: loop.CapabilitiesRegistry.Get:input_type -> loop.GetRequest
	6,  // 13: loop.CapabilitiesRegistry.GetTrigger:input_type -> loop.GetTriggerRequest
	8,  // 14: loop.CapabilitiesRegistry.GetExecutable:input_type -> loop.GetExecutableRequest
	20, // 15: loop.CapabilitiesRegistry.List:input_type -> google.protobuf.Empty
	12, // 16: loop.CapabilitiesRegistry.Add:input_type -> loop.AddRequest
	13, // 17: loop.CapabilitiesRegistry.Remove:input_type -> loop.RemoveRequest
	3,  // 18: loop.CapabilitiesRegistry.LocalNode:output_type -> loop.NodeReply
	3,  // 19: loop.CapabilitiesRegistry.NodeByPeerID:output_type -> loop.NodeReply
	15, // 20: loop.CapabilitiesRegistry.ConfigForCapability:output_type -> loop.ConfigForCapabilityReply
	18, // 21: loop.CapabilitiesRegistry.DONsForCapability:output_type -> loop.DONForCapabilityReply
	5,  // 22: loop.CapabilitiesRegistry.Get:output_type -> loop.GetReply
	7,  // 23: loop.CapabilitiesRegistry.GetTrigger:output_type -> loop.GetTriggerReply
	9,  // 24: loop.CapabilitiesRegistry.GetExecutable:output_type -> loop.GetExecutableReply
	10, // 25: loop.CapabilitiesRegistry.List:output_type -> loop.ListReply
	20, // 26: loop.CapabilitiesRegistry.Add:output_type -> google.protobuf.Empty
	20, // 27: loop.CapabilitiesRegistry.Remove:output_type -> google.protobuf.Empty
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_capabilities_registry_proto_init() }
func file_capabilities_registry_proto_init() {
	if File_capabilities_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_registry_proto_rawDesc), len(file_capabilities_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capabilities_registry_proto_goTypes,
		DependencyIndexes: file_capabilities_registry_proto_depIdxs,
		EnumInfos:         file_capabilities_registry_proto_enumTypes,
		MessageInfos:      file_capabilities_registry_proto_msgTypes,
	}.Build()
	File_capabilities_registry_proto = out.File
	file_capabilities_registry_proto_goTypes = nil
	file_capabilities_registry_proto_depIdxs = nil
}
