// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chain_capabilities.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the on-chain Solana account structure.
type SolanaAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of lamports assigned to this account
	Lamports uint64 `protobuf:"varint,1,opt,name=lamports,proto3" json:"lamports,omitempty"`
	// Pubkey of the program this account has been assigned to (32 bytes)
	Owner []byte `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Data associated with the account
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Boolean indicating if the account contains a program (and is strictly read-only)
	Executable bool `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	// The epoch at which this account will next owe rent (stored as a string if you need arbitrary precision)
	RentEpoch     string `protobuf:"bytes,5,opt,name=rent_epoch,json=rentEpoch,proto3" json:"rent_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolanaAccount) Reset() {
	*x = SolanaAccount{}
	mi := &file_chain_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolanaAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolanaAccount) ProtoMessage() {}

func (x *SolanaAccount) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolanaAccount.ProtoReflect.Descriptor instead.
func (*SolanaAccount) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *SolanaAccount) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *SolanaAccount) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SolanaAccount) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SolanaAccount) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *SolanaAccount) GetRentEpoch() string {
	if x != nil {
		return x.RentEpoch
	}
	return ""
}

// Request for FindProgramAddress
type FindProgramAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One or more seed values used to derive the program address
	Seeds [][]byte `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	// The 32-byte program ID
	ProgramId     []byte `protobuf:"bytes,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProgramAddressRequest) Reset() {
	*x = FindProgramAddressRequest{}
	mi := &file_chain_capabilities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProgramAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProgramAddressRequest) ProtoMessage() {}

func (x *FindProgramAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProgramAddressRequest.ProtoReflect.Descriptor instead.
func (*FindProgramAddressRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{1}
}

func (x *FindProgramAddressRequest) GetSeeds() [][]byte {
	if x != nil {
		return x.Seeds
	}
	return nil
}

func (x *FindProgramAddressRequest) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

// Response for FindProgramAddress
type FindProgramAddressReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The derived 32-byte program address
	Address       []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProgramAddressReply) Reset() {
	*x = FindProgramAddressReply{}
	mi := &file_chain_capabilities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProgramAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProgramAddressReply) ProtoMessage() {}

func (x *FindProgramAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProgramAddressReply.ProtoReflect.Descriptor instead.
func (*FindProgramAddressReply) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{2}
}

func (x *FindProgramAddressReply) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// Request for GetAccountData
type GetAccountDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 32-byte program ID (or account address)
	ProgramId     []byte `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDataRequest) Reset() {
	*x = GetAccountDataRequest{}
	mi := &file_chain_capabilities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDataRequest) ProtoMessage() {}

func (x *GetAccountDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDataRequest.ProtoReflect.Descriptor instead.
func (*GetAccountDataRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountDataRequest) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

// Response for GetAccountData
type GetAccountDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *SolanaAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDataReply) Reset() {
	*x = GetAccountDataReply{}
	mi := &file_chain_capabilities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDataReply) ProtoMessage() {}

func (x *GetAccountDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDataReply.ProtoReflect.Descriptor instead.
func (*GetAccountDataReply) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountDataReply) GetAccount() *SolanaAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

// Request for GetMultipleAccountData
type GetMultipleAccountDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of 32-byte program IDs (or account addresses)
	ProgramIds    [][]byte `protobuf:"bytes,1,rep,name=program_ids,json=programIds,proto3" json:"program_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleAccountDataRequest) Reset() {
	*x = GetMultipleAccountDataRequest{}
	mi := &file_chain_capabilities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleAccountDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleAccountDataRequest) ProtoMessage() {}

func (x *GetMultipleAccountDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleAccountDataRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleAccountDataRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{5}
}

func (x *GetMultipleAccountDataRequest) GetProgramIds() [][]byte {
	if x != nil {
		return x.ProgramIds
	}
	return nil
}

// Response for GetMultipleAccountData
type GetMultipleAccountDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*SolanaAccount       `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleAccountDataReply) Reset() {
	*x = GetMultipleAccountDataReply{}
	mi := &file_chain_capabilities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleAccountDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleAccountDataReply) ProtoMessage() {}

func (x *GetMultipleAccountDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleAccountDataReply.ProtoReflect.Descriptor instead.
func (*GetMultipleAccountDataReply) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{6}
}

func (x *GetMultipleAccountDataReply) GetAccounts() []*SolanaAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// Request for ReadContract
type ReadContractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the EVM contract method
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Encoded parameters for the contract call
	EncodedParams []byte `protobuf:"bytes,2,opt,name=encoded_params,json=encodedParams,proto3" json:"encoded_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadContractRequest) Reset() {
	*x = ReadContractRequest{}
	mi := &file_chain_capabilities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadContractRequest) ProtoMessage() {}

func (x *ReadContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadContractRequest.ProtoReflect.Descriptor instead.
func (*ReadContractRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{7}
}

func (x *ReadContractRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReadContractRequest) GetEncodedParams() []byte {
	if x != nil {
		return x.EncodedParams
	}
	return nil
}

// Response for ReadContract
type ReadContractReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded return data from the contract call
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadContractReply) Reset() {
	*x = ReadContractReply{}
	mi := &file_chain_capabilities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadContractReply) ProtoMessage() {}

func (x *ReadContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadContractReply.ProtoReflect.Descriptor instead.
func (*ReadContractReply) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_proto_rawDescGZIP(), []int{8}
}

func (x *ReadContractReply) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_chain_capabilities_proto protoreflect.FileDescriptor

const file_chain_capabilities_proto_rawDesc = "" +
	"\n" +
	"\x18chain_capabilities.proto\x12\x04loop\"\x94\x01\n" +
	"\rSolanaAccount\x12\x1a\n" +
	"\blamports\x18\x01 \x01(\x04R\blamports\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\fR\x05owner\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\x12\x1d\n" +
	"\n" +
	"rent_epoch\x18\x05 \x01(\tR\trentEpoch\"P\n" +
	"\x19FindProgramAddressRequest\x12\x14\n" +
	"\x05seeds\x18\x01 \x03(\fR\x05seeds\x12\x1d\n" +
	"\n" +
	"program_id\x18\x02 \x01(\fR\tprogramId\"3\n" +
	"\x17FindProgramAddressReply\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\"6\n" +
	"\x15GetAccountDataRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\fR\tprogramId\"D\n" +
	"\x13GetAccountDataReply\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.loop.SolanaAccountR\aaccount\"@\n" +
	"\x1dGetMultipleAccountDataRequest\x12\x1f\n" +
	"\vprogram_ids\x18\x01 \x03(\fR\n" +
	"programIds\"N\n" +
	"\x1bGetMultipleAccountDataReply\x12/\n" +
	"\baccounts\x18\x01 \x03(\v2\x13.loop.SolanaAccountR\baccounts\"T\n" +
	"\x13ReadContractRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12%\n" +
	"\x0eencoded_params\x18\x02 \x01(\fR\rencodedParams\"+\n" +
	"\x11ReadContractReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\xd9\x02\n" +
	"\x11ChainCapabilities\x12T\n" +
	"\x12FindProgramAddress\x12\x1f.loop.FindProgramAddressRequest\x1a\x1d.loop.FindProgramAddressReply\x12H\n" +
	"\x0eGetAccountData\x12\x1b.loop.GetAccountDataRequest\x1a\x19.loop.GetAccountDataReply\x12`\n" +
	"\x16GetMultipleAccountData\x12#.loop.GetMultipleAccountDataRequest\x1a!.loop.GetMultipleAccountDataReply\x12B\n" +
	"\fReadContract\x12\x19.loop.ReadContractRequest\x1a\x17.loop.ReadContractReplyBCZAgithub.com/smartcontractkit/chainlink-common/pkg/loop/internal/pbb\x06proto3"

var (
	file_chain_capabilities_proto_rawDescOnce sync.Once
	file_chain_capabilities_proto_rawDescData []byte
)

func file_chain_capabilities_proto_rawDescGZIP() []byte {
	file_chain_capabilities_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_proto_rawDesc), len(file_chain_capabilities_proto_rawDesc)))
	})
	return file_chain_capabilities_proto_rawDescData
}

var file_chain_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chain_capabilities_proto_goTypes = []any{
	(*SolanaAccount)(nil),                 // 0: loop.SolanaAccount
	(*FindProgramAddressRequest)(nil),     // 1: loop.FindProgramAddressRequest
	(*FindProgramAddressReply)(nil),       // 2: loop.FindProgramAddressReply
	(*GetAccountDataRequest)(nil),         // 3: loop.GetAccountDataRequest
	(*GetAccountDataReply)(nil),           // 4: loop.GetAccountDataReply
	(*GetMultipleAccountDataRequest)(nil), // 5: loop.GetMultipleAccountDataRequest
	(*GetMultipleAccountDataReply)(nil),   // 6: loop.GetMultipleAccountDataReply
	(*ReadContractRequest)(nil),           // 7: loop.ReadContractRequest
	(*ReadContractReply)(nil),             // 8: loop.ReadContractReply
}
var file_chain_capabilities_proto_depIdxs = []int32{
	0, // 0: loop.GetAccountDataReply.account:type_name -> loop.SolanaAccount
	0, // 1: loop.GetMultipleAccountDataReply.accounts:type_name -> loop.SolanaAccount
	1, // 2: loop.ChainCapabilities.FindProgramAddress:input_type -> loop.FindProgramAddressRequest
	3, // 3: loop.ChainCapabilities.GetAccountData:input_type -> loop.GetAccountDataRequest
	5, // 4: loop.ChainCapabilities.GetMultipleAccountData:input_type -> loop.GetMultipleAccountDataRequest
	7, // 5: loop.ChainCapabilities.ReadContract:input_type -> loop.ReadContractRequest
	2, // 6: loop.ChainCapabilities.FindProgramAddress:output_type -> loop.FindProgramAddressReply
	4, // 7: loop.ChainCapabilities.GetAccountData:output_type -> loop.GetAccountDataReply
	6, // 8: loop.ChainCapabilities.GetMultipleAccountData:output_type -> loop.GetMultipleAccountDataReply
	8, // 9: loop.ChainCapabilities.ReadContract:output_type -> loop.ReadContractReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chain_capabilities_proto_init() }
func file_chain_capabilities_proto_init() {
	if File_chain_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_proto_rawDesc), len(file_chain_capabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_capabilities_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_proto_msgTypes,
	}.Build()
	File_chain_capabilities_proto = out.File
	file_chain_capabilities_proto_goTypes = nil
	file_chain_capabilities_proto_depIdxs = nil
}
