// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: loop/internal/pb/contract_reader.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComparisonOperator int32

const (
	ComparisonOperator_Eq  ComparisonOperator = 0
	ComparisonOperator_Neq ComparisonOperator = 1
	ComparisonOperator_Gt  ComparisonOperator = 2
	ComparisonOperator_Lt  ComparisonOperator = 3
	ComparisonOperator_Gte ComparisonOperator = 4
	ComparisonOperator_Lte ComparisonOperator = 5
)

// Enum value maps for ComparisonOperator.
var (
	ComparisonOperator_name = map[int32]string{
		0: "Eq",
		1: "Neq",
		2: "Gt",
		3: "Lt",
		4: "Gte",
		5: "Lte",
	}
	ComparisonOperator_value = map[string]int32{
		"Eq":  0,
		"Neq": 1,
		"Gt":  2,
		"Lt":  3,
		"Gte": 4,
		"Lte": 5,
	}
)

func (x ComparisonOperator) Enum() *ComparisonOperator {
	p := new(ComparisonOperator)
	*p = x
	return p
}

func (x ComparisonOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[0].Descriptor()
}

func (ComparisonOperator) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[0]
}

func (x ComparisonOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonOperator.Descriptor instead.
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{0}
}

type BooleanOperator int32

const (
	BooleanOperator_AND BooleanOperator = 0
	BooleanOperator_OR  BooleanOperator = 1
)

// Enum value maps for BooleanOperator.
var (
	BooleanOperator_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	BooleanOperator_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x BooleanOperator) Enum() *BooleanOperator {
	p := new(BooleanOperator)
	*p = x
	return p
}

func (x BooleanOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BooleanOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[1].Descriptor()
}

func (BooleanOperator) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[1]
}

func (x BooleanOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BooleanOperator.Descriptor instead.
func (BooleanOperator) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{1}
}

type Confidence int32

const (
	Confidence_Unconfirmed Confidence = 0
	Confidence_Finalized   Confidence = 1
)

// Enum value maps for Confidence.
var (
	Confidence_name = map[int32]string{
		0: "Unconfirmed",
		1: "Finalized",
	}
	Confidence_value = map[string]int32{
		"Unconfirmed": 0,
		"Finalized":   1,
	}
)

func (x Confidence) Enum() *Confidence {
	p := new(Confidence)
	*p = x
	return p
}

func (x Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[2].Descriptor()
}

func (Confidence) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[2]
}

func (x Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confidence.Descriptor instead.
func (Confidence) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{2}
}

// CursorDirection defines the direction for cursor-based data fetching.
type CursorDirection int32

const (
	CursorDirection_Preceding CursorDirection = 0
	CursorDirection_Following CursorDirection = 1
)

// Enum value maps for CursorDirection.
var (
	CursorDirection_name = map[int32]string{
		0: "Preceding",
		1: "Following",
	}
	CursorDirection_value = map[string]int32{
		"Preceding": 0,
		"Following": 1,
	}
)

func (x CursorDirection) Enum() *CursorDirection {
	p := new(CursorDirection)
	*p = x
	return p
}

func (x CursorDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CursorDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[3].Descriptor()
}

func (CursorDirection) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[3]
}

func (x CursorDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CursorDirection.Descriptor instead.
func (CursorDirection) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{3}
}

type SortDirection int32

const (
	SortDirection_Asc  SortDirection = 0
	SortDirection_Desc SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "Asc",
		1: "Desc",
	}
	SortDirection_value = map[string]int32{
		"Asc":  0,
		"Desc": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[4].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[4]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{4}
}

type SortType int32

const (
	SortType_SortTimestamp SortType = 0
	SortType_SortBlock     SortType = 1
	SortType_SortSequence  SortType = 2
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "SortTimestamp",
		1: "SortBlock",
		2: "SortSequence",
	}
	SortType_value = map[string]int32{
		"SortTimestamp": 0,
		"SortBlock":     1,
		"SortSequence":  2,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_loop_internal_pb_contract_reader_proto_enumTypes[5].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_loop_internal_pb_contract_reader_proto_enumTypes[5]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{5}
}

// GetLatestValueRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.GetLatestValue].
type GetLatestValueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadIdentifier string                 `protobuf:"bytes,1,opt,name=read_identifier,json=readIdentifier,proto3" json:"read_identifier,omitempty"`
	Confidence     Confidence             `protobuf:"varint,2,opt,name=confidence,proto3,enum=loop.Confidence" json:"confidence,omitempty"`
	Params         *VersionedBytes        `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	AsValueType    bool                   `protobuf:"varint,4,opt,name=as_value_type,json=asValueType,proto3" json:"as_value_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLatestValueRequest) Reset() {
	*x = GetLatestValueRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestValueRequest) ProtoMessage() {}

func (x *GetLatestValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestValueRequest.ProtoReflect.Descriptor instead.
func (*GetLatestValueRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestValueRequest) GetReadIdentifier() string {
	if x != nil {
		return x.ReadIdentifier
	}
	return ""
}

func (x *GetLatestValueRequest) GetConfidence() Confidence {
	if x != nil {
		return x.Confidence
	}
	return Confidence_Unconfirmed
}

func (x *GetLatestValueRequest) GetParams() *VersionedBytes {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetLatestValueRequest) GetAsValueType() bool {
	if x != nil {
		return x.AsValueType
	}
	return false
}

// BatchGetLatestValuesRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchGetLatestValues].
type BatchGetLatestValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ContractBatch       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetLatestValuesRequest) Reset() {
	*x = BatchGetLatestValuesRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetLatestValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetLatestValuesRequest) ProtoMessage() {}

func (x *BatchGetLatestValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetLatestValuesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetLatestValuesRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetLatestValuesRequest) GetRequests() []*ContractBatch {
	if x != nil {
		return x.Requests
	}
	return nil
}

// QueryKeyRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.QueryKey].
type QueryKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *BoundContract         `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Filter        *QueryKeyFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	LimitAndSort  *LimitAndSort          `protobuf:"bytes,3,opt,name=limit_and_sort,json=limitAndSort,proto3" json:"limit_and_sort,omitempty"`
	AsValueType   bool                   `protobuf:"varint,4,opt,name=as_value_type,json=asValueType,proto3" json:"as_value_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKeyRequest) Reset() {
	*x = QueryKeyRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKeyRequest) ProtoMessage() {}

func (x *QueryKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKeyRequest.ProtoReflect.Descriptor instead.
func (*QueryKeyRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{2}
}

func (x *QueryKeyRequest) GetContract() *BoundContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *QueryKeyRequest) GetFilter() *QueryKeyFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryKeyRequest) GetLimitAndSort() *LimitAndSort {
	if x != nil {
		return x.LimitAndSort
	}
	return nil
}

func (x *QueryKeyRequest) GetAsValueType() bool {
	if x != nil {
		return x.AsValueType
	}
	return false
}

// QueryKeysRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.QueryKeys].
type QueryKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*ContractKeyFilter   `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	LimitAndSort  *LimitAndSort          `protobuf:"bytes,2,opt,name=limit_and_sort,json=limitAndSort,proto3" json:"limit_and_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKeysRequest) Reset() {
	*x = QueryKeysRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKeysRequest) ProtoMessage() {}

func (x *QueryKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKeysRequest.ProtoReflect.Descriptor instead.
func (*QueryKeysRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{3}
}

func (x *QueryKeysRequest) GetFilters() []*ContractKeyFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryKeysRequest) GetLimitAndSort() *LimitAndSort {
	if x != nil {
		return x.LimitAndSort
	}
	return nil
}

type ContractKeyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *BoundContract         `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Filter        *QueryKeyFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	AsValueType   bool                   `protobuf:"varint,4,opt,name=as_value_type,json=asValueType,proto3" json:"as_value_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractKeyFilter) Reset() {
	*x = ContractKeyFilter{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractKeyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractKeyFilter) ProtoMessage() {}

func (x *ContractKeyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractKeyFilter.ProtoReflect.Descriptor instead.
func (*ContractKeyFilter) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{4}
}

func (x *ContractKeyFilter) GetContract() *BoundContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ContractKeyFilter) GetFilter() *QueryKeyFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ContractKeyFilter) GetAsValueType() bool {
	if x != nil {
		return x.AsValueType
	}
	return false
}

// BindRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.Bind].
type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*BoundContract       `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{5}
}

func (x *BindRequest) GetBindings() []*BoundContract {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// UnbindRequest has arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.Unbind].
type UnbindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*BoundContract       `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRequest) Reset() {
	*x = UnbindRequest{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRequest) ProtoMessage() {}

func (x *UnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRequest.ProtoReflect.Descriptor instead.
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{6}
}

func (x *UnbindRequest) GetBindings() []*BoundContract {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// GetLatestValueReply has return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.GetLatestValue].
type GetLatestValueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetVal        *VersionedBytes        `protobuf:"bytes,1,opt,name=ret_val,json=retVal,proto3" json:"ret_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestValueReply) Reset() {
	*x = GetLatestValueReply{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestValueReply) ProtoMessage() {}

func (x *GetLatestValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestValueReply.ProtoReflect.Descriptor instead.
func (*GetLatestValueReply) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{7}
}

func (x *GetLatestValueReply) GetRetVal() *VersionedBytes {
	if x != nil {
		return x.RetVal
	}
	return nil
}

// GetLatestValueWithHeadDataReply has return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.GetLatestValueWithHeadData].
type GetLatestValueWithHeadDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetVal        *VersionedBytes        `protobuf:"bytes,1,opt,name=ret_val,json=retVal,proto3" json:"ret_val,omitempty"`
	HeadData      *Head                  `protobuf:"bytes,2,opt,name=head_data,json=headData,proto3" json:"head_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestValueWithHeadDataReply) Reset() {
	*x = GetLatestValueWithHeadDataReply{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestValueWithHeadDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestValueWithHeadDataReply) ProtoMessage() {}

func (x *GetLatestValueWithHeadDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestValueWithHeadDataReply.ProtoReflect.Descriptor instead.
func (*GetLatestValueWithHeadDataReply) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{8}
}

func (x *GetLatestValueWithHeadDataReply) GetRetVal() *VersionedBytes {
	if x != nil {
		return x.RetVal
	}
	return nil
}

func (x *GetLatestValueWithHeadDataReply) GetHeadData() *Head {
	if x != nil {
		return x.HeadData
	}
	return nil
}

// BatchGetLatestValuesReply has return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchGetLatestValues].
type BatchGetLatestValuesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ContractBatchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetLatestValuesReply) Reset() {
	*x = BatchGetLatestValuesReply{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetLatestValuesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetLatestValuesReply) ProtoMessage() {}

func (x *BatchGetLatestValuesReply) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetLatestValuesReply.ProtoReflect.Descriptor instead.
func (*BatchGetLatestValuesReply) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetLatestValuesReply) GetResults() []*ContractBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// QueryKeyReply has return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.QueryKey].
type QueryKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequences     []*Sequence            `protobuf:"bytes,1,rep,name=sequences,proto3" json:"sequences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKeyReply) Reset() {
	*x = QueryKeyReply{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKeyReply) ProtoMessage() {}

func (x *QueryKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKeyReply.ProtoReflect.Descriptor instead.
func (*QueryKeyReply) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{10}
}

func (x *QueryKeyReply) GetSequences() []*Sequence {
	if x != nil {
		return x.Sequences
	}
	return nil
}

// QueryKeysReply has return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.QueryKeys].
type QueryKeysReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequences     []*SequenceWithKey     `protobuf:"bytes,1,rep,name=sequences,proto3" json:"sequences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKeysReply) Reset() {
	*x = QueryKeysReply{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKeysReply) ProtoMessage() {}

func (x *QueryKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKeysReply.ProtoReflect.Descriptor instead.
func (*QueryKeysReply) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{11}
}

func (x *QueryKeysReply) GetSequences() []*SequenceWithKey {
	if x != nil {
		return x.Sequences
	}
	return nil
}

// ContractBatch is gRPC adapter for the BatchGetLatestValuesRequest struct map value [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchGetLatestValuesRequest].
type ContractBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *BoundContract         `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Reads         []*BatchRead           `protobuf:"bytes,2,rep,name=reads,proto3" json:"reads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractBatch) Reset() {
	*x = ContractBatch{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractBatch) ProtoMessage() {}

func (x *ContractBatch) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractBatch.ProtoReflect.Descriptor instead.
func (*ContractBatch) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{12}
}

func (x *ContractBatch) GetContract() *BoundContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ContractBatch) GetReads() []*BatchRead {
	if x != nil {
		return x.Reads
	}
	return nil
}

// BatchCall is gRPC adapter for the GetLatestValueRequest struct [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchCall].
type BatchRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadName      string                 `protobuf:"bytes,1,opt,name=read_name,json=readName,proto3" json:"read_name,omitempty"`
	Params        *VersionedBytes        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	ReturnVal     *VersionedBytes        `protobuf:"bytes,3,opt,name=return_val,json=returnVal,proto3" json:"return_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRead) Reset() {
	*x = BatchRead{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRead) ProtoMessage() {}

func (x *BatchRead) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRead.ProtoReflect.Descriptor instead.
func (*BatchRead) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{13}
}

func (x *BatchRead) GetReadName() string {
	if x != nil {
		return x.ReadName
	}
	return ""
}

func (x *BatchRead) GetParams() *VersionedBytes {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BatchRead) GetReturnVal() *VersionedBytes {
	if x != nil {
		return x.ReturnVal
	}
	return nil
}

// ContractBatchResult is part of return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchGetLatestValues].
type ContractBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *BoundContract         `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Results       []*BatchReadResult     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractBatchResult) Reset() {
	*x = ContractBatchResult{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractBatchResult) ProtoMessage() {}

func (x *ContractBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractBatchResult.ProtoReflect.Descriptor instead.
func (*ContractBatchResult) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{14}
}

func (x *ContractBatchResult) GetContract() *BoundContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ContractBatchResult) GetResults() []*BatchReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// BatchCallResult is part of return arguments for [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.BatchGetLatestValues].
type BatchReadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadName      string                 `protobuf:"bytes,1,opt,name=read_name,json=readName,proto3" json:"read_name,omitempty"`
	ReturnVal     *VersionedBytes        `protobuf:"bytes,2,opt,name=return_val,json=returnVal,proto3" json:"return_val,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReadResult) Reset() {
	*x = BatchReadResult{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReadResult) ProtoMessage() {}

func (x *BatchReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReadResult.ProtoReflect.Descriptor instead.
func (*BatchReadResult) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{15}
}

func (x *BatchReadResult) GetReadName() string {
	if x != nil {
		return x.ReadName
	}
	return ""
}

func (x *BatchReadResult) GetReturnVal() *VersionedBytes {
	if x != nil {
		return x.ReturnVal
	}
	return nil
}

func (x *BatchReadResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Head is gRPC adapter for the Head struct [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.Head].
type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        string                 `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{16}
}

func (x *Head) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *Head) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Head) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Head is gRPC adapter for the Head struct [github.com/smartcontractkit/chainlink-common/pkg/types.ContractReader.Sequence].
type Sequence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceCursor string                 `protobuf:"bytes,1,opt,name=sequence_cursor,json=sequenceCursor,proto3" json:"sequence_cursor,omitempty"`
	Head           *Head                  `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Data           *VersionedBytes        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sequence) Reset() {
	*x = Sequence{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sequence) ProtoMessage() {}

func (x *Sequence) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sequence.ProtoReflect.Descriptor instead.
func (*Sequence) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{17}
}

func (x *Sequence) GetSequenceCursor() string {
	if x != nil {
		return x.SequenceCursor
	}
	return ""
}

func (x *Sequence) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Sequence) GetData() *VersionedBytes {
	if x != nil {
		return x.Data
	}
	return nil
}

type SequenceWithKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceCursor string                 `protobuf:"bytes,1,opt,name=sequence_cursor,json=sequenceCursor,proto3" json:"sequence_cursor,omitempty"`
	Head           *Head                  `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Data           *VersionedBytes        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Key            string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SequenceWithKey) Reset() {
	*x = SequenceWithKey{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceWithKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceWithKey) ProtoMessage() {}

func (x *SequenceWithKey) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceWithKey.ProtoReflect.Descriptor instead.
func (*SequenceWithKey) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{18}
}

func (x *SequenceWithKey) GetSequenceCursor() string {
	if x != nil {
		return x.SequenceCursor
	}
	return ""
}

func (x *SequenceWithKey) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *SequenceWithKey) GetData() *VersionedBytes {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SequenceWithKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// BoundContract represents a [github.com/smartcontractkit/chainlink-common/pkg/types.BoundContract].
type BoundContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundContract) Reset() {
	*x = BoundContract{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundContract) ProtoMessage() {}

func (x *BoundContract) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundContract.ProtoReflect.Descriptor instead.
func (*BoundContract) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{19}
}

func (x *BoundContract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BoundContract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryKeyFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Expressions are lightweight orm like DSL defined for filtering over common blockchain primitives.
	Expression    []*Expression `protobuf:"bytes,2,rep,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKeyFilter) Reset() {
	*x = QueryKeyFilter{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKeyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKeyFilter) ProtoMessage() {}

func (x *QueryKeyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKeyFilter.ProtoReflect.Descriptor instead.
func (*QueryKeyFilter) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{20}
}

func (x *QueryKeyFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueryKeyFilter) GetExpression() []*Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

// Expression encapsulates a single unit of filtering logic, which can be a common blockchain primitive or a composite of boolean expressions.
// This allows for both simple and more complex nested expressions.
type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Evaluator:
	//
	//	*Expression_Primitive
	//	*Expression_BooleanExpression
	Evaluator     isExpression_Evaluator `protobuf_oneof:"evaluator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{21}
}

func (x *Expression) GetEvaluator() isExpression_Evaluator {
	if x != nil {
		return x.Evaluator
	}
	return nil
}

func (x *Expression) GetPrimitive() *Primitive {
	if x != nil {
		if x, ok := x.Evaluator.(*Expression_Primitive); ok {
			return x.Primitive
		}
	}
	return nil
}

func (x *Expression) GetBooleanExpression() *BooleanExpression {
	if x != nil {
		if x, ok := x.Evaluator.(*Expression_BooleanExpression); ok {
			return x.BooleanExpression
		}
	}
	return nil
}

type isExpression_Evaluator interface {
	isExpression_Evaluator()
}

type Expression_Primitive struct {
	Primitive *Primitive `protobuf:"bytes,1,opt,name=primitive,proto3,oneof"`
}

type Expression_BooleanExpression struct {
	BooleanExpression *BooleanExpression `protobuf:"bytes,2,opt,name=boolean_expression,json=booleanExpression,proto3,oneof"`
}

func (*Expression_Primitive) isExpression_Evaluator() {}

func (*Expression_BooleanExpression) isExpression_Evaluator() {}

type BooleanExpression struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BooleanOperator BooleanOperator        `protobuf:"varint,1,opt,name=boolean_operator,json=booleanOperator,proto3,enum=loop.BooleanOperator" json:"boolean_operator,omitempty"`
	Expression      []*Expression          `protobuf:"bytes,2,rep,name=expression,proto3" json:"expression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BooleanExpression) Reset() {
	*x = BooleanExpression{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanExpression) ProtoMessage() {}

func (x *BooleanExpression) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanExpression.ProtoReflect.Descriptor instead.
func (*BooleanExpression) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{22}
}

func (x *BooleanExpression) GetBooleanOperator() BooleanOperator {
	if x != nil {
		return x.BooleanOperator
	}
	return BooleanOperator_AND
}

func (x *BooleanExpression) GetExpression() []*Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

type And struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          []*Expression          `protobuf:"bytes,1,rep,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *And) Reset() {
	*x = And{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *And) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*And) ProtoMessage() {}

func (x *And) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use And.ProtoReflect.Descriptor instead.
func (*And) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{23}
}

func (x *And) GetExpr() []*Expression {
	if x != nil {
		return x.Expr
	}
	return nil
}

type Or struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          []*Expression          `protobuf:"bytes,1,rep,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Or) Reset() {
	*x = Or{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Or) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Or) ProtoMessage() {}

func (x *Or) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Or.ProtoReflect.Descriptor instead.
func (*Or) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{24}
}

func (x *Or) GetExpr() []*Expression {
	if x != nil {
		return x.Expr
	}
	return nil
}

type ValueComparator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *VersionedBytes        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Operator      ComparisonOperator     `protobuf:"varint,2,opt,name=operator,proto3,enum=loop.ComparisonOperator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueComparator) Reset() {
	*x = ValueComparator{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueComparator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueComparator) ProtoMessage() {}

func (x *ValueComparator) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueComparator.ProtoReflect.Descriptor instead.
func (*ValueComparator) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{25}
}

func (x *ValueComparator) GetValue() *VersionedBytes {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ValueComparator) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_Eq
}

type Comparator struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValueComparators []*ValueComparator     `protobuf:"bytes,2,rep,name=value_comparators,json=valueComparators,proto3" json:"value_comparators,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Comparator) Reset() {
	*x = Comparator{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparator) ProtoMessage() {}

func (x *Comparator) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparator.ProtoReflect.Descriptor instead.
func (*Comparator) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{26}
}

func (x *Comparator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Comparator) GetValueComparators() []*ValueComparator {
	if x != nil {
		return x.ValueComparators
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   string                 `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Operator      ComparisonOperator     `protobuf:"varint,2,opt,name=operator,proto3,enum=loop.ComparisonOperator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{27}
}

func (x *Block) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *Block) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_Eq
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operator      ComparisonOperator     `protobuf:"varint,2,opt,name=operator,proto3,enum=loop.ComparisonOperator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{28}
}

func (x *Timestamp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Timestamp) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_Eq
}

type TxHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxHash) Reset() {
	*x = TxHash{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxHash) ProtoMessage() {}

func (x *TxHash) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxHash.ProtoReflect.Descriptor instead.
func (*TxHash) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{29}
}

func (x *TxHash) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

// Primitive defines the basic building blocks for filter conditions based around fundamental blockchain concepts.
type Primitive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Primitive:
	//
	//	*Primitive_Comparator
	//	*Primitive_Block
	//	*Primitive_Confidence
	//	*Primitive_Timestamp
	//	*Primitive_TxHash
	Primitive     isPrimitive_Primitive `protobuf_oneof:"primitive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Primitive) Reset() {
	*x = Primitive{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Primitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primitive) ProtoMessage() {}

func (x *Primitive) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primitive.ProtoReflect.Descriptor instead.
func (*Primitive) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{30}
}

func (x *Primitive) GetPrimitive() isPrimitive_Primitive {
	if x != nil {
		return x.Primitive
	}
	return nil
}

func (x *Primitive) GetComparator() *Comparator {
	if x != nil {
		if x, ok := x.Primitive.(*Primitive_Comparator); ok {
			return x.Comparator
		}
	}
	return nil
}

func (x *Primitive) GetBlock() *Block {
	if x != nil {
		if x, ok := x.Primitive.(*Primitive_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *Primitive) GetConfidence() Confidence {
	if x != nil {
		if x, ok := x.Primitive.(*Primitive_Confidence); ok {
			return x.Confidence
		}
	}
	return Confidence_Unconfirmed
}

func (x *Primitive) GetTimestamp() *Timestamp {
	if x != nil {
		if x, ok := x.Primitive.(*Primitive_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Primitive) GetTxHash() *TxHash {
	if x != nil {
		if x, ok := x.Primitive.(*Primitive_TxHash); ok {
			return x.TxHash
		}
	}
	return nil
}

type isPrimitive_Primitive interface {
	isPrimitive_Primitive()
}

type Primitive_Comparator struct {
	Comparator *Comparator `protobuf:"bytes,1,opt,name=comparator,proto3,oneof"`
}

type Primitive_Block struct {
	Block *Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type Primitive_Confidence struct {
	Confidence Confidence `protobuf:"varint,3,opt,name=confidence,proto3,enum=loop.Confidence,oneof"`
}

type Primitive_Timestamp struct {
	Timestamp *Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3,oneof"`
}

type Primitive_TxHash struct {
	TxHash *TxHash `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3,oneof"`
}

func (*Primitive_Comparator) isPrimitive_Primitive() {}

func (*Primitive_Block) isPrimitive_Primitive() {}

func (*Primitive_Confidence) isPrimitive_Primitive() {}

func (*Primitive_Timestamp) isPrimitive_Primitive() {}

func (*Primitive_TxHash) isPrimitive_Primitive() {}

// Limit defines a structure for limiting the results of a query, including optional cursor-based pagination.
type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Direction     *CursorDirection       `protobuf:"varint,2,opt,name=direction,proto3,enum=loop.CursorDirection,oneof" json:"direction,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{31}
}

func (x *Limit) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *Limit) GetDirection() CursorDirection {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return CursorDirection_Preceding
}

func (x *Limit) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SortBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortType      SortType               `protobuf:"varint,1,opt,name=sort_type,json=sortType,proto3,enum=loop.SortType" json:"sort_type,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=loop.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortBy) Reset() {
	*x = SortBy{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortBy) ProtoMessage() {}

func (x *SortBy) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortBy.ProtoReflect.Descriptor instead.
func (*SortBy) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{32}
}

func (x *SortBy) GetSortType() SortType {
	if x != nil {
		return x.SortType
	}
	return SortType_SortTimestamp
}

func (x *SortBy) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_Asc
}

// LimitAndSort combines sorting criteria with pagination limits.
type LimitAndSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortBy        []*SortBy              `protobuf:"bytes,1,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // A list of sorting criteria.
	Limit         *Limit                 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // Pagination limit and direction.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitAndSort) Reset() {
	*x = LimitAndSort{}
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitAndSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitAndSort) ProtoMessage() {}

func (x *LimitAndSort) ProtoReflect() protoreflect.Message {
	mi := &file_loop_internal_pb_contract_reader_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitAndSort.ProtoReflect.Descriptor instead.
func (*LimitAndSort) Descriptor() ([]byte, []int) {
	return file_loop_internal_pb_contract_reader_proto_rawDescGZIP(), []int{33}
}

func (x *LimitAndSort) GetSortBy() []*SortBy {
	if x != nil {
		return x.SortBy
	}
	return nil
}

func (x *LimitAndSort) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

var File_loop_internal_pb_contract_reader_proto protoreflect.FileDescriptor

const file_loop_internal_pb_contract_reader_proto_rawDesc = "" +
	"\n" +
	"&loop/internal/pb/contract_reader.proto\x12\x04loop\x1a\x1cloop/internal/pb/codec.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc4\x01\n" +
	"\x15GetLatestValueRequest\x12'\n" +
	"\x0fread_identifier\x18\x01 \x01(\tR\x0ereadIdentifier\x120\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x0e2\x10.loop.ConfidenceR\n" +
	"confidence\x12,\n" +
	"\x06params\x18\x03 \x01(\v2\x14.loop.VersionedBytesR\x06params\x12\"\n" +
	"\ras_value_type\x18\x04 \x01(\bR\vasValueType\"N\n" +
	"\x1bBatchGetLatestValuesRequest\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.loop.ContractBatchR\brequests\"\xce\x01\n" +
	"\x0fQueryKeyRequest\x12/\n" +
	"\bcontract\x18\x01 \x01(\v2\x13.loop.BoundContractR\bcontract\x12,\n" +
	"\x06filter\x18\x02 \x01(\v2\x14.loop.QueryKeyFilterR\x06filter\x128\n" +
	"\x0elimit_and_sort\x18\x03 \x01(\v2\x12.loop.LimitAndSortR\flimitAndSort\x12\"\n" +
	"\ras_value_type\x18\x04 \x01(\bR\vasValueType\"\x7f\n" +
	"\x10QueryKeysRequest\x121\n" +
	"\afilters\x18\x01 \x03(\v2\x17.loop.ContractKeyFilterR\afilters\x128\n" +
	"\x0elimit_and_sort\x18\x02 \x01(\v2\x12.loop.LimitAndSortR\flimitAndSort\"\x96\x01\n" +
	"\x11ContractKeyFilter\x12/\n" +
	"\bcontract\x18\x01 \x01(\v2\x13.loop.BoundContractR\bcontract\x12,\n" +
	"\x06filter\x18\x02 \x01(\v2\x14.loop.QueryKeyFilterR\x06filter\x12\"\n" +
	"\ras_value_type\x18\x04 \x01(\bR\vasValueType\">\n" +
	"\vBindRequest\x12/\n" +
	"\bbindings\x18\x01 \x03(\v2\x13.loop.BoundContractR\bbindings\"@\n" +
	"\rUnbindRequest\x12/\n" +
	"\bbindings\x18\x01 \x03(\v2\x13.loop.BoundContractR\bbindings\"D\n" +
	"\x13GetLatestValueReply\x12-\n" +
	"\aret_val\x18\x01 \x01(\v2\x14.loop.VersionedBytesR\x06retVal\"y\n" +
	"\x1fGetLatestValueWithHeadDataReply\x12-\n" +
	"\aret_val\x18\x01 \x01(\v2\x14.loop.VersionedBytesR\x06retVal\x12'\n" +
	"\thead_data\x18\x02 \x01(\v2\n" +
	".loop.HeadR\bheadData\"P\n" +
	"\x19BatchGetLatestValuesReply\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.loop.ContractBatchResultR\aresults\"=\n" +
	"\rQueryKeyReply\x12,\n" +
	"\tsequences\x18\x01 \x03(\v2\x0e.loop.SequenceR\tsequences\"E\n" +
	"\x0eQueryKeysReply\x123\n" +
	"\tsequences\x18\x01 \x03(\v2\x15.loop.SequenceWithKeyR\tsequences\"g\n" +
	"\rContractBatch\x12/\n" +
	"\bcontract\x18\x01 \x01(\v2\x13.loop.BoundContractR\bcontract\x12%\n" +
	"\x05reads\x18\x02 \x03(\v2\x0f.loop.BatchReadR\x05reads\"\x8b\x01\n" +
	"\tBatchRead\x12\x1b\n" +
	"\tread_name\x18\x01 \x01(\tR\breadName\x12,\n" +
	"\x06params\x18\x02 \x01(\v2\x14.loop.VersionedBytesR\x06params\x123\n" +
	"\n" +
	"return_val\x18\x03 \x01(\v2\x14.loop.VersionedBytesR\treturnVal\"w\n" +
	"\x13ContractBatchResult\x12/\n" +
	"\bcontract\x18\x01 \x01(\v2\x13.loop.BoundContractR\bcontract\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.loop.BatchReadResultR\aresults\"y\n" +
	"\x0fBatchReadResult\x12\x1b\n" +
	"\tread_name\x18\x01 \x01(\tR\breadName\x123\n" +
	"\n" +
	"return_val\x18\x02 \x01(\v2\x14.loop.VersionedBytesR\treturnVal\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x04Head\x12\x16\n" +
	"\x06height\x18\x01 \x01(\tR\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"}\n" +
	"\bSequence\x12'\n" +
	"\x0fsequence_cursor\x18\x01 \x01(\tR\x0esequenceCursor\x12\x1e\n" +
	"\x04head\x18\x02 \x01(\v2\n" +
	".loop.HeadR\x04head\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.loop.VersionedBytesR\x04data\"\x96\x01\n" +
	"\x0fSequenceWithKey\x12'\n" +
	"\x0fsequence_cursor\x18\x01 \x01(\tR\x0esequenceCursor\x12\x1e\n" +
	"\x04head\x18\x02 \x01(\v2\n" +
	".loop.HeadR\x04head\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.loop.VersionedBytesR\x04data\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"=\n" +
	"\rBoundContract\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"T\n" +
	"\x0eQueryKeyFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\n" +
	"expression\x18\x02 \x03(\v2\x10.loop.ExpressionR\n" +
	"expression\"\x94\x01\n" +
	"\n" +
	"Expression\x12/\n" +
	"\tprimitive\x18\x01 \x01(\v2\x0f.loop.PrimitiveH\x00R\tprimitive\x12H\n" +
	"\x12boolean_expression\x18\x02 \x01(\v2\x17.loop.BooleanExpressionH\x00R\x11booleanExpressionB\v\n" +
	"\tevaluator\"\x87\x01\n" +
	"\x11BooleanExpression\x12@\n" +
	"\x10boolean_operator\x18\x01 \x01(\x0e2\x15.loop.BooleanOperatorR\x0fbooleanOperator\x120\n" +
	"\n" +
	"expression\x18\x02 \x03(\v2\x10.loop.ExpressionR\n" +
	"expression\"+\n" +
	"\x03And\x12$\n" +
	"\x04expr\x18\x01 \x03(\v2\x10.loop.ExpressionR\x04expr\"*\n" +
	"\x02Or\x12$\n" +
	"\x04expr\x18\x01 \x03(\v2\x10.loop.ExpressionR\x04expr\"s\n" +
	"\x0fValueComparator\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.loop.VersionedBytesR\x05value\x124\n" +
	"\boperator\x18\x02 \x01(\x0e2\x18.loop.ComparisonOperatorR\boperator\"d\n" +
	"\n" +
	"Comparator\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\x11value_comparators\x18\x02 \x03(\v2\x15.loop.ValueComparatorR\x10valueComparators\"`\n" +
	"\x05Block\x12!\n" +
	"\fblock_number\x18\x01 \x01(\tR\vblockNumber\x124\n" +
	"\boperator\x18\x02 \x01(\x0e2\x18.loop.ComparisonOperatorR\boperator\"_\n" +
	"\tTimestamp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x124\n" +
	"\boperator\x18\x02 \x01(\x0e2\x18.loop.ComparisonOperatorR\boperator\"!\n" +
	"\x06TxHash\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\xff\x01\n" +
	"\tPrimitive\x122\n" +
	"\n" +
	"comparator\x18\x01 \x01(\v2\x10.loop.ComparatorH\x00R\n" +
	"comparator\x12#\n" +
	"\x05block\x18\x02 \x01(\v2\v.loop.BlockH\x00R\x05block\x122\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x0e2\x10.loop.ConfidenceH\x00R\n" +
	"confidence\x12/\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x0f.loop.TimestampH\x00R\ttimestamp\x12'\n" +
	"\atx_hash\x18\x05 \x01(\v2\f.loop.TxHashH\x00R\x06txHashB\v\n" +
	"\tprimitive\"\x8d\x01\n" +
	"\x05Limit\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x128\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x15.loop.CursorDirectionH\x01R\tdirection\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05countB\t\n" +
	"\a_cursorB\f\n" +
	"\n" +
	"_direction\"h\n" +
	"\x06SortBy\x12+\n" +
	"\tsort_type\x18\x01 \x01(\x0e2\x0e.loop.SortTypeR\bsortType\x121\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x13.loop.SortDirectionR\tdirection\"X\n" +
	"\fLimitAndSort\x12%\n" +
	"\asort_by\x18\x01 \x03(\v2\f.loop.SortByR\x06sortBy\x12!\n" +
	"\x05limit\x18\x02 \x01(\v2\v.loop.LimitR\x05limit*G\n" +
	"\x12ComparisonOperator\x12\x06\n" +
	"\x02Eq\x10\x00\x12\a\n" +
	"\x03Neq\x10\x01\x12\x06\n" +
	"\x02Gt\x10\x02\x12\x06\n" +
	"\x02Lt\x10\x03\x12\a\n" +
	"\x03Gte\x10\x04\x12\a\n" +
	"\x03Lte\x10\x05*\"\n" +
	"\x0fBooleanOperator\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01*,\n" +
	"\n" +
	"Confidence\x12\x0f\n" +
	"\vUnconfirmed\x10\x00\x12\r\n" +
	"\tFinalized\x10\x01*/\n" +
	"\x0fCursorDirection\x12\r\n" +
	"\tPreceding\x10\x00\x12\r\n" +
	"\tFollowing\x10\x01*\"\n" +
	"\rSortDirection\x12\a\n" +
	"\x03Asc\x10\x00\x12\b\n" +
	"\x04Desc\x10\x01*>\n" +
	"\bSortType\x12\x11\n" +
	"\rSortTimestamp\x10\x00\x12\r\n" +
	"\tSortBlock\x10\x01\x12\x10\n" +
	"\fSortSequence\x10\x022\x83\x04\n" +
	"\x0eContractReader\x12J\n" +
	"\x0eGetLatestValue\x12\x1b.loop.GetLatestValueRequest\x1a\x19.loop.GetLatestValueReply\"\x00\x12b\n" +
	"\x1aGetLatestValueWithHeadData\x12\x1b.loop.GetLatestValueRequest\x1a%.loop.GetLatestValueWithHeadDataReply\"\x00\x12\\\n" +
	"\x14BatchGetLatestValues\x12!.loop.BatchGetLatestValuesRequest\x1a\x1f.loop.BatchGetLatestValuesReply\"\x00\x128\n" +
	"\bQueryKey\x12\x15.loop.QueryKeyRequest\x1a\x13.loop.QueryKeyReply\"\x00\x12;\n" +
	"\tQueryKeys\x12\x16.loop.QueryKeysRequest\x1a\x14.loop.QueryKeysReply\"\x00\x123\n" +
	"\x04Bind\x12\x11.loop.BindRequest\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x06Unbind\x12\x13.loop.UnbindRequest\x1a\x16.google.protobuf.Empty\"\x00BCZAgithub.com/smartcontractkit/chainlink-common/pkg/loop/internal/pbb\x06proto3"

var (
	file_loop_internal_pb_contract_reader_proto_rawDescOnce sync.Once
	file_loop_internal_pb_contract_reader_proto_rawDescData []byte
)

func file_loop_internal_pb_contract_reader_proto_rawDescGZIP() []byte {
	file_loop_internal_pb_contract_reader_proto_rawDescOnce.Do(func() {
		file_loop_internal_pb_contract_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loop_internal_pb_contract_reader_proto_rawDesc), len(file_loop_internal_pb_contract_reader_proto_rawDesc)))
	})
	return file_loop_internal_pb_contract_reader_proto_rawDescData
}

var file_loop_internal_pb_contract_reader_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_loop_internal_pb_contract_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_loop_internal_pb_contract_reader_proto_goTypes = []any{
	(ComparisonOperator)(0),                 // 0: loop.ComparisonOperator
	(BooleanOperator)(0),                    // 1: loop.BooleanOperator
	(Confidence)(0),                         // 2: loop.Confidence
	(CursorDirection)(0),                    // 3: loop.CursorDirection
	(SortDirection)(0),                      // 4: loop.SortDirection
	(SortType)(0),                           // 5: loop.SortType
	(*GetLatestValueRequest)(nil),           // 6: loop.GetLatestValueRequest
	(*BatchGetLatestValuesRequest)(nil),     // 7: loop.BatchGetLatestValuesRequest
	(*QueryKeyRequest)(nil),                 // 8: loop.QueryKeyRequest
	(*QueryKeysRequest)(nil),                // 9: loop.QueryKeysRequest
	(*ContractKeyFilter)(nil),               // 10: loop.ContractKeyFilter
	(*BindRequest)(nil),                     // 11: loop.BindRequest
	(*UnbindRequest)(nil),                   // 12: loop.UnbindRequest
	(*GetLatestValueReply)(nil),             // 13: loop.GetLatestValueReply
	(*GetLatestValueWithHeadDataReply)(nil), // 14: loop.GetLatestValueWithHeadDataReply
	(*BatchGetLatestValuesReply)(nil),       // 15: loop.BatchGetLatestValuesReply
	(*QueryKeyReply)(nil),                   // 16: loop.QueryKeyReply
	(*QueryKeysReply)(nil),                  // 17: loop.QueryKeysReply
	(*ContractBatch)(nil),                   // 18: loop.ContractBatch
	(*BatchRead)(nil),                       // 19: loop.BatchRead
	(*ContractBatchResult)(nil),             // 20: loop.ContractBatchResult
	(*BatchReadResult)(nil),                 // 21: loop.BatchReadResult
	(*Head)(nil),                            // 22: loop.Head
	(*Sequence)(nil),                        // 23: loop.Sequence
	(*SequenceWithKey)(nil),                 // 24: loop.SequenceWithKey
	(*BoundContract)(nil),                   // 25: loop.BoundContract
	(*QueryKeyFilter)(nil),                  // 26: loop.QueryKeyFilter
	(*Expression)(nil),                      // 27: loop.Expression
	(*BooleanExpression)(nil),               // 28: loop.BooleanExpression
	(*And)(nil),                             // 29: loop.And
	(*Or)(nil),                              // 30: loop.Or
	(*ValueComparator)(nil),                 // 31: loop.ValueComparator
	(*Comparator)(nil),                      // 32: loop.Comparator
	(*Block)(nil),                           // 33: loop.Block
	(*Timestamp)(nil),                       // 34: loop.Timestamp
	(*TxHash)(nil),                          // 35: loop.TxHash
	(*Primitive)(nil),                       // 36: loop.Primitive
	(*Limit)(nil),                           // 37: loop.Limit
	(*SortBy)(nil),                          // 38: loop.SortBy
	(*LimitAndSort)(nil),                    // 39: loop.LimitAndSort
	(*VersionedBytes)(nil),                  // 40: loop.VersionedBytes
	(*emptypb.Empty)(nil),                   // 41: google.protobuf.Empty
}
var file_loop_internal_pb_contract_reader_proto_depIdxs = []int32{
	2,  // 0: loop.GetLatestValueRequest.confidence:type_name -> loop.Confidence
	40, // 1: loop.GetLatestValueRequest.params:type_name -> loop.VersionedBytes
	18, // 2: loop.BatchGetLatestValuesRequest.requests:type_name -> loop.ContractBatch
	25, // 3: loop.QueryKeyRequest.contract:type_name -> loop.BoundContract
	26, // 4: loop.QueryKeyRequest.filter:type_name -> loop.QueryKeyFilter
	39, // 5: loop.QueryKeyRequest.limit_and_sort:type_name -> loop.LimitAndSort
	10, // 6: loop.QueryKeysRequest.filters:type_name -> loop.ContractKeyFilter
	39, // 7: loop.QueryKeysRequest.limit_and_sort:type_name -> loop.LimitAndSort
	25, // 8: loop.ContractKeyFilter.contract:type_name -> loop.BoundContract
	26, // 9: loop.ContractKeyFilter.filter:type_name -> loop.QueryKeyFilter
	25, // 10: loop.BindRequest.bindings:type_name -> loop.BoundContract
	25, // 11: loop.UnbindRequest.bindings:type_name -> loop.BoundContract
	40, // 12: loop.GetLatestValueReply.ret_val:type_name -> loop.VersionedBytes
	40, // 13: loop.GetLatestValueWithHeadDataReply.ret_val:type_name -> loop.VersionedBytes
	22, // 14: loop.GetLatestValueWithHeadDataReply.head_data:type_name -> loop.Head
	20, // 15: loop.BatchGetLatestValuesReply.results:type_name -> loop.ContractBatchResult
	23, // 16: loop.QueryKeyReply.sequences:type_name -> loop.Sequence
	24, // 17: loop.QueryKeysReply.sequences:type_name -> loop.SequenceWithKey
	25, // 18: loop.ContractBatch.contract:type_name -> loop.BoundContract
	19, // 19: loop.ContractBatch.reads:type_name -> loop.BatchRead
	40, // 20: loop.BatchRead.params:type_name -> loop.VersionedBytes
	40, // 21: loop.BatchRead.return_val:type_name -> loop.VersionedBytes
	25, // 22: loop.ContractBatchResult.contract:type_name -> loop.BoundContract
	21, // 23: loop.ContractBatchResult.results:type_name -> loop.BatchReadResult
	40, // 24: loop.BatchReadResult.return_val:type_name -> loop.VersionedBytes
	22, // 25: loop.Sequence.head:type_name -> loop.Head
	40, // 26: loop.Sequence.data:type_name -> loop.VersionedBytes
	22, // 27: loop.SequenceWithKey.head:type_name -> loop.Head
	40, // 28: loop.SequenceWithKey.data:type_name -> loop.VersionedBytes
	27, // 29: loop.QueryKeyFilter.expression:type_name -> loop.Expression
	36, // 30: loop.Expression.primitive:type_name -> loop.Primitive
	28, // 31: loop.Expression.boolean_expression:type_name -> loop.BooleanExpression
	1,  // 32: loop.BooleanExpression.boolean_operator:type_name -> loop.BooleanOperator
	27, // 33: loop.BooleanExpression.expression:type_name -> loop.Expression
	27, // 34: loop.And.expr:type_name -> loop.Expression
	27, // 35: loop.Or.expr:type_name -> loop.Expression
	40, // 36: loop.ValueComparator.value:type_name -> loop.VersionedBytes
	0,  // 37: loop.ValueComparator.operator:type_name -> loop.ComparisonOperator
	31, // 38: loop.Comparator.value_comparators:type_name -> loop.ValueComparator
	0,  // 39: loop.Block.operator:type_name -> loop.ComparisonOperator
	0,  // 40: loop.Timestamp.operator:type_name -> loop.ComparisonOperator
	32, // 41: loop.Primitive.comparator:type_name -> loop.Comparator
	33, // 42: loop.Primitive.block:type_name -> loop.Block
	2,  // 43: loop.Primitive.confidence:type_name -> loop.Confidence
	34, // 44: loop.Primitive.timestamp:type_name -> loop.Timestamp
	35, // 45: loop.Primitive.tx_hash:type_name -> loop.TxHash
	3,  // 46: loop.Limit.direction:type_name -> loop.CursorDirection
	5,  // 47: loop.SortBy.sort_type:type_name -> loop.SortType
	4,  // 48: loop.SortBy.direction:type_name -> loop.SortDirection
	38, // 49: loop.LimitAndSort.sort_by:type_name -> loop.SortBy
	37, // 50: loop.LimitAndSort.limit:type_name -> loop.Limit
	6,  // 51: loop.ContractReader.GetLatestValue:input_type -> loop.GetLatestValueRequest
	6,  // 52: loop.ContractReader.GetLatestValueWithHeadData:input_type -> loop.GetLatestValueRequest
	7,  // 53: loop.ContractReader.BatchGetLatestValues:input_type -> loop.BatchGetLatestValuesRequest
	8,  // 54: loop.ContractReader.QueryKey:input_type -> loop.QueryKeyRequest
	9,  // 55: loop.ContractReader.QueryKeys:input_type -> loop.QueryKeysRequest
	11, // 56: loop.ContractReader.Bind:input_type -> loop.BindRequest
	12, // 57: loop.ContractReader.Unbind:input_type -> loop.UnbindRequest
	13, // 58: loop.ContractReader.GetLatestValue:output_type -> loop.GetLatestValueReply
	14, // 59: loop.ContractReader.GetLatestValueWithHeadData:output_type -> loop.GetLatestValueWithHeadDataReply
	15, // 60: loop.ContractReader.BatchGetLatestValues:output_type -> loop.BatchGetLatestValuesReply
	16, // 61: loop.ContractReader.QueryKey:output_type -> loop.QueryKeyReply
	17, // 62: loop.ContractReader.QueryKeys:output_type -> loop.QueryKeysReply
	41, // 63: loop.ContractReader.Bind:output_type -> google.protobuf.Empty
	41, // 64: loop.ContractReader.Unbind:output_type -> google.protobuf.Empty
	58, // [58:65] is the sub-list for method output_type
	51, // [51:58] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_loop_internal_pb_contract_reader_proto_init() }
func file_loop_internal_pb_contract_reader_proto_init() {
	if File_loop_internal_pb_contract_reader_proto != nil {
		return
	}
	file_loop_internal_pb_codec_proto_init()
	file_loop_internal_pb_contract_reader_proto_msgTypes[21].OneofWrappers = []any{
		(*Expression_Primitive)(nil),
		(*Expression_BooleanExpression)(nil),
	}
	file_loop_internal_pb_contract_reader_proto_msgTypes[30].OneofWrappers = []any{
		(*Primitive_Comparator)(nil),
		(*Primitive_Block)(nil),
		(*Primitive_Confidence)(nil),
		(*Primitive_Timestamp)(nil),
		(*Primitive_TxHash)(nil),
	}
	file_loop_internal_pb_contract_reader_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loop_internal_pb_contract_reader_proto_rawDesc), len(file_loop_internal_pb_contract_reader_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loop_internal_pb_contract_reader_proto_goTypes,
		DependencyIndexes: file_loop_internal_pb_contract_reader_proto_depIdxs,
		EnumInfos:         file_loop_internal_pb_contract_reader_proto_enumTypes,
		MessageInfos:      file_loop_internal_pb_contract_reader_proto_msgTypes,
	}.Build()
	File_loop_internal_pb_contract_reader_proto = out.File
	file_loop_internal_pb_contract_reader_proto_goTypes = nil
	file_loop_internal_pb_contract_reader_proto_depIdxs = nil
}
