dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
packages:
  github.com/smartcontractkit/chainlink-common/pkg/types:
    interfaces:
      ContractReader:
        config:
          dir: "{{ .InterfaceDir }}/../../mocks"
  github.com/smartcontractkit/chainlink-common/pkg/capabilities/datastreams:
    interfaces:
      ReportCodec:
  github.com/smartcontractkit/chainlink-common/pkg/loop/internal/types:
    interfaces:
      Relayer:
        config:
          dir: "{{ .InterfaceDir }}/../../mocks"
  github.com/smartcontractkit/chainlink-common/pkg/monitoring:
    config:
      dir: "{{ .InterfaceDir }}"
      filename: "{{ .InterfaceName | snakecase }}_mock.go"
      inpackage: true
      mockname: "{{ .InterfaceName }}Mock"
    interfaces:
      Metrics:
      Source:
      SourceFactory:
      Exporter:
      ExporterFactory:
  github.com/smartcontractkit/chainlink-common/pkg/types/ccip:
    interfaces:
      OffRampReader:
        config:
          filename: offramp_reader_mock.go
  github.com/smartcontractkit/chainlink-common/pkg/types/core:
    interfaces:
      CapabilitiesRegistry:
      Relayer:
  github.com/smartcontractkit/chainlink-common/pkg/beholder/internal:
    interfaces:
      OTLPExporter:
