dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
fail-on-missing: true
packages:
  github.com/smartcontractkit/chainlink-common/pkg/capabilities/datastreams:
    interfaces:
      ReportCodec:
  github.com/smartcontractkit/chainlink-common/pkg/loop/internal/types:
    interfaces:
      Relayer:
        config:
          dir: "{{ .InterfaceDir }}/../../mocks"
  github.com/smartcontractkit/chainlink-common/pkg/types/ccip:
    interfaces:
      OffRampReader:
        config:
          filename: offramp_reader_mock.go
  github.com/smartcontractkit/chainlink-common/pkg/types:
    interfaces:
      ContractReader:
      EVMService:
      TONService:
  github.com/smartcontractkit/chainlink-common/pkg/types/core:
    interfaces:
      CapabilitiesRegistry:
      Relayer:
      GatewayConnector:
      GatewayConnectorHandler:
      RelayerSet:
  github.com/smartcontractkit/chainlink-common/pkg/beholder/internal:
    interfaces:
      OTLPExporter: {}
  github.com/smartcontractkit/chainlink-common/pkg/chipingress:
    interfaces:
      Client: {}
  github.com/smartcontractkit/chainlink-common/pkg/workflows/wasm/host:
    interfaces:
      ModuleV1: {}
      ModuleV2: {}
      ExecutionHelper:
        config:
          inpackage: true
          filename: "mock_{{.InterfaceName | snakecase}}_test.go"
          mockname: "Mock{{.InterfaceName}}"
          dir: "{{.InterfaceDir}}"
  github.com/smartcontractkit/chainlink-common/pkg/custmsg:
    interfaces:
      MessageEmitter:
        config:
          inpackage: true
          filename: "mock_{{.InterfaceName | snakecase}}_test.go"
          mockname: "mock{{.InterfaceName}}"
          dir: "{{.InterfaceDir}}"
