// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: triggers.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinatedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowID     string                 `protobuf:"bytes,1,opt,name=workflowID,proto3" json:"workflowID,omitempty"`
	TriggerCapID   string                 `protobuf:"bytes,2,opt,name=triggerCapID,proto3" json:"triggerCapID,omitempty"`
	TriggerIndex   int64                  `protobuf:"varint,3,opt,name=triggerIndex,proto3" json:"triggerIndex,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observedAt,proto3" json:"observedAt,omitempty"`
	Deadline       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,6,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	Event          *TriggerResponse       `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoordinatedEvent) Reset() {
	*x = CoordinatedEvent{}
	mi := &file_triggers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatedEvent) ProtoMessage() {}

func (x *CoordinatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatedEvent.ProtoReflect.Descriptor instead.
func (*CoordinatedEvent) Descriptor() ([]byte, []int) {
	return file_triggers_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatedEvent) GetWorkflowID() string {
	if x != nil {
		return x.WorkflowID
	}
	return ""
}

func (x *CoordinatedEvent) GetTriggerCapID() string {
	if x != nil {
		return x.TriggerCapID
	}
	return ""
}

func (x *CoordinatedEvent) GetTriggerIndex() int64 {
	if x != nil {
		return x.TriggerIndex
	}
	return 0
}

func (x *CoordinatedEvent) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *CoordinatedEvent) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CoordinatedEvent) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CoordinatedEvent) GetEvent() *TriggerResponse {
	if x != nil {
		return x.Event
	}
	return nil
}

type ConsensusQueueObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CoordinatedEvent    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusQueueObservation) Reset() {
	*x = ConsensusQueueObservation{}
	mi := &file_triggers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusQueueObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusQueueObservation) ProtoMessage() {}

func (x *ConsensusQueueObservation) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusQueueObservation.ProtoReflect.Descriptor instead.
func (*ConsensusQueueObservation) Descriptor() ([]byte, []int) {
	return file_triggers_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusQueueObservation) GetEvents() []*CoordinatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ConsensusQueueReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CoordinatedEvent    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusQueueReport) Reset() {
	*x = ConsensusQueueReport{}
	mi := &file_triggers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusQueueReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusQueueReport) ProtoMessage() {}

func (x *ConsensusQueueReport) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusQueueReport.ProtoReflect.Descriptor instead.
func (*ConsensusQueueReport) Descriptor() ([]byte, []int) {
	return file_triggers_proto_rawDescGZIP(), []int{2}
}

func (x *ConsensusQueueReport) GetEvents() []*CoordinatedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_triggers_proto protoreflect.FileDescriptor

const file_triggers_proto_rawDesc = "" +
	"\n" +
	"\x0etriggers.proto\x12\btriggers\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12capabilities.proto\"\xcb\x02\n" +
	"\x10CoordinatedEvent\x12\x1e\n" +
	"\n" +
	"workflowID\x18\x01 \x01(\tR\n" +
	"workflowID\x12\"\n" +
	"\ftriggerCapID\x18\x02 \x01(\tR\ftriggerCapID\x12\"\n" +
	"\ftriggerIndex\x18\x03 \x01(\x03R\ftriggerIndex\x12:\n" +
	"\n" +
	"observedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12&\n" +
	"\x0esequenceNumber\x18\x06 \x01(\x04R\x0esequenceNumber\x123\n" +
	"\x05event\x18\a \x01(\v2\x1d.capabilities.TriggerResponseR\x05event\"O\n" +
	"\x19ConsensusQueueObservation\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.triggers.CoordinatedEventR\x06events\"J\n" +
	"\x14ConsensusQueueReport\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.triggers.CoordinatedEventR\x06eventsBBZ@github.com/smartcontractkit/chainlink-common/pkg/capabilities/pbb\x06proto3"

var (
	file_triggers_proto_rawDescOnce sync.Once
	file_triggers_proto_rawDescData []byte
)

func file_triggers_proto_rawDescGZIP() []byte {
	file_triggers_proto_rawDescOnce.Do(func() {
		file_triggers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_triggers_proto_rawDesc), len(file_triggers_proto_rawDesc)))
	})
	return file_triggers_proto_rawDescData
}

var file_triggers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_triggers_proto_goTypes = []any{
	(*CoordinatedEvent)(nil),          // 0: triggers.CoordinatedEvent
	(*ConsensusQueueObservation)(nil), // 1: triggers.ConsensusQueueObservation
	(*ConsensusQueueReport)(nil),      // 2: triggers.ConsensusQueueReport
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
	(*TriggerResponse)(nil),           // 4: capabilities.TriggerResponse
}
var file_triggers_proto_depIdxs = []int32{
	3, // 0: triggers.CoordinatedEvent.observedAt:type_name -> google.protobuf.Timestamp
	3, // 1: triggers.CoordinatedEvent.deadline:type_name -> google.protobuf.Timestamp
	4, // 2: triggers.CoordinatedEvent.event:type_name -> capabilities.TriggerResponse
	0, // 3: triggers.ConsensusQueueObservation.events:type_name -> triggers.CoordinatedEvent
	0, // 4: triggers.ConsensusQueueReport.events:type_name -> triggers.CoordinatedEvent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_triggers_proto_init() }
func file_triggers_proto_init() {
	if File_triggers_proto != nil {
		return
	}
	file_capabilities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_triggers_proto_rawDesc), len(file_triggers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_triggers_proto_goTypes,
		DependencyIndexes: file_triggers_proto_depIdxs,
		MessageInfos:      file_triggers_proto_msgTypes,
	}.Build()
	File_triggers_proto = out.File
	file_triggers_proto_goTypes = nil
	file_triggers_proto_depIdxs = nil
}
