fail-on-missing: true
packages:
  github.com/smartcontractkit/chainlink-common/pkg/monitoring:
    config:
      dir: "{{ .InterfaceDir }}"
      filename: "{{ .InterfaceName | snakecase }}_mock.go"
      inpackage: true
      mockname: "{{ .InterfaceName }}Mock"
    interfaces:
      Metrics:
      Source:
      SourceFactory:
      Exporter:
      ExporterFactory:
