// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: aptos.proto

package aptos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Aptos_LedgerVersion_FullMethodName       = "/loop.aptos.Aptos/LedgerVersion"
	Aptos_AccountAPTBalance_FullMethodName   = "/loop.aptos.Aptos/AccountAPTBalance"
	Aptos_AccountTransactions_FullMethodName = "/loop.aptos.Aptos/AccountTransactions"
	Aptos_View_FullMethodName                = "/loop.aptos.Aptos/View"
	Aptos_EventsByHandle_FullMethodName      = "/loop.aptos.Aptos/EventsByHandle"
	Aptos_TransactionByHash_FullMethodName   = "/loop.aptos.Aptos/TransactionByHash"
	Aptos_SubmitTransaction_FullMethodName   = "/loop.aptos.Aptos/SubmitTransaction"
)

// AptosClient is the client API for Aptos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AptosClient interface {
	LedgerVersion(ctx context.Context, in *LedgerVersionRequest, opts ...grpc.CallOption) (*LedgerVersionReply, error)
	AccountAPTBalance(ctx context.Context, in *AccountAPTBalanceRequest, opts ...grpc.CallOption) (*AccountAPTBalanceReply, error)
	AccountTransactions(ctx context.Context, in *AccountTransactionsRequest, opts ...grpc.CallOption) (*AccountTransactionsReply, error)
	View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewReply, error)
	EventsByHandle(ctx context.Context, in *EventsByHandleRequest, opts ...grpc.CallOption) (*EventsByHandleReply, error)
	TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error)
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionReply, error)
}

type aptosClient struct {
	cc grpc.ClientConnInterface
}

func NewAptosClient(cc grpc.ClientConnInterface) AptosClient {
	return &aptosClient{cc}
}

func (c *aptosClient) LedgerVersion(ctx context.Context, in *LedgerVersionRequest, opts ...grpc.CallOption) (*LedgerVersionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerVersionReply)
	err := c.cc.Invoke(ctx, Aptos_LedgerVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) AccountAPTBalance(ctx context.Context, in *AccountAPTBalanceRequest, opts ...grpc.CallOption) (*AccountAPTBalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountAPTBalanceReply)
	err := c.cc.Invoke(ctx, Aptos_AccountAPTBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) AccountTransactions(ctx context.Context, in *AccountTransactionsRequest, opts ...grpc.CallOption) (*AccountTransactionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountTransactionsReply)
	err := c.cc.Invoke(ctx, Aptos_AccountTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewReply)
	err := c.cc.Invoke(ctx, Aptos_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) EventsByHandle(ctx context.Context, in *EventsByHandleRequest, opts ...grpc.CallOption) (*EventsByHandleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsByHandleReply)
	err := c.cc.Invoke(ctx, Aptos_EventsByHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) TransactionByHash(ctx context.Context, in *TransactionByHashRequest, opts ...grpc.CallOption) (*TransactionByHashReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionByHashReply)
	err := c.cc.Invoke(ctx, Aptos_TransactionByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aptosClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTransactionReply)
	err := c.cc.Invoke(ctx, Aptos_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AptosServer is the server API for Aptos service.
// All implementations must embed UnimplementedAptosServer
// for forward compatibility.
type AptosServer interface {
	LedgerVersion(context.Context, *LedgerVersionRequest) (*LedgerVersionReply, error)
	AccountAPTBalance(context.Context, *AccountAPTBalanceRequest) (*AccountAPTBalanceReply, error)
	AccountTransactions(context.Context, *AccountTransactionsRequest) (*AccountTransactionsReply, error)
	View(context.Context, *ViewRequest) (*ViewReply, error)
	EventsByHandle(context.Context, *EventsByHandleRequest) (*EventsByHandleReply, error)
	TransactionByHash(context.Context, *TransactionByHashRequest) (*TransactionByHashReply, error)
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionReply, error)
	mustEmbedUnimplementedAptosServer()
}

// UnimplementedAptosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAptosServer struct{}

func (UnimplementedAptosServer) LedgerVersion(context.Context, *LedgerVersionRequest) (*LedgerVersionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LedgerVersion not implemented")
}
func (UnimplementedAptosServer) AccountAPTBalance(context.Context, *AccountAPTBalanceRequest) (*AccountAPTBalanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountAPTBalance not implemented")
}
func (UnimplementedAptosServer) AccountTransactions(context.Context, *AccountTransactionsRequest) (*AccountTransactionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountTransactions not implemented")
}
func (UnimplementedAptosServer) View(context.Context, *ViewRequest) (*ViewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedAptosServer) EventsByHandle(context.Context, *EventsByHandleRequest) (*EventsByHandleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EventsByHandle not implemented")
}
func (UnimplementedAptosServer) TransactionByHash(context.Context, *TransactionByHashRequest) (*TransactionByHashReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionByHash not implemented")
}
func (UnimplementedAptosServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedAptosServer) mustEmbedUnimplementedAptosServer() {}
func (UnimplementedAptosServer) testEmbeddedByValue()               {}

// UnsafeAptosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AptosServer will
// result in compilation errors.
type UnsafeAptosServer interface {
	mustEmbedUnimplementedAptosServer()
}

func RegisterAptosServer(s grpc.ServiceRegistrar, srv AptosServer) {
	// If the following call panics, it indicates UnimplementedAptosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aptos_ServiceDesc, srv)
}

func _Aptos_LedgerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).LedgerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_LedgerVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).LedgerVersion(ctx, req.(*LedgerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_AccountAPTBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountAPTBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).AccountAPTBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_AccountAPTBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).AccountAPTBalance(ctx, req.(*AccountAPTBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_AccountTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).AccountTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_AccountTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).AccountTransactions(ctx, req.(*AccountTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).View(ctx, req.(*ViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_EventsByHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsByHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).EventsByHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_EventsByHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).EventsByHandle(ctx, req.(*EventsByHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_TransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).TransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_TransactionByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).TransactionByHash(ctx, req.(*TransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aptos_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AptosServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aptos_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AptosServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aptos_ServiceDesc is the grpc.ServiceDesc for Aptos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aptos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loop.aptos.Aptos",
	HandlerType: (*AptosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LedgerVersion",
			Handler:    _Aptos_LedgerVersion_Handler,
		},
		{
			MethodName: "AccountAPTBalance",
			Handler:    _Aptos_AccountAPTBalance_Handler,
		},
		{
			MethodName: "AccountTransactions",
			Handler:    _Aptos_AccountTransactions_Handler,
		},
		{
			MethodName: "View",
			Handler:    _Aptos_View_Handler,
		},
		{
			MethodName: "EventsByHandle",
			Handler:    _Aptos_EventsByHandle_Handler,
		},
		{
			MethodName: "TransactionByHash",
			Handler:    _Aptos_TransactionByHash_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _Aptos_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aptos.proto",
}
