// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: capabilities/v2/chain-capabilities/evm/capability/capability.proto

package evm

import (
	chain_service "github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/chain-capabilities/evm/chain-service"
	_ "github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc/pkg/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_capabilities_v2_chain_capabilities_evm_capability_capability_proto protoreflect.FileDescriptor

const file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_rawDesc = "" +
	"\n" +
	"Bcapabilities/v2/chain-capabilities/evm/capability/capability.proto\x12\x0ecre.sdk.v2.evm\x1a\x1bgoogle/protobuf/empty.proto\x1a0capabilities/v2/protoc/pkg/pb/cre_metadata.proto\x1a>capabilities/v2/chain-capabilities/evm/chain-service/evm.proto2\xa6\t\n" +
	"\x06Client\x12p\n" +
	"\fCallContract\x120.loop.chain_capabilities.evm.CallContractRequest\x1a..loop.chain_capabilities.evm.CallContractReply\x12j\n" +
	"\n" +
	"FilterLogs\x12..loop.chain_capabilities.evm.FilterLogsRequest\x1a,.loop.chain_capabilities.evm.FilterLogsReply\x12g\n" +
	"\tBalanceAt\x12-.loop.chain_capabilities.evm.BalanceAtRequest\x1a+.loop.chain_capabilities.evm.BalanceAtReply\x12m\n" +
	"\vEstimateGas\x12/.loop.chain_capabilities.evm.EstimateGasRequest\x1a-.loop.chain_capabilities.evm.EstimateGasReply\x12\x88\x01\n" +
	"\x14GetTransactionByHash\x128.loop.chain_capabilities.evm.GetTransactionByHashRequest\x1a6.loop.chain_capabilities.evm.GetTransactionByHashReply\x12\x8b\x01\n" +
	"\x15GetTransactionReceipt\x129.loop.chain_capabilities.evm.GetTransactionReceiptRequest\x1a7.loop.chain_capabilities.evm.GetTransactionReceiptReply\x12j\n" +
	"\x16LatestAndFinalizedHead\x12\x16.google.protobuf.Empty\x1a8.loop.chain_capabilities.evm.LatestAndFinalizedHeadReply\x12|\n" +
	"\x10QueryTrackedLogs\x124.loop.chain_capabilities.evm.QueryTrackedLogsRequest\x1a2.loop.chain_capabilities.evm.QueryTrackedLogsReply\x12f\n" +
	"\x13RegisterLogTracking\x127.loop.chain_capabilities.evm.RegisterLogTrackingRequest\x1a\x16.google.protobuf.Empty\x12j\n" +
	"\x15UnregisterLogTracking\x129.loop.chain_capabilities.evm.UnregisterLogTrackingRequest\x1a\x16.google.protobuf.Empty\x1a\x0f\x82\xb5\x18\v\x12\tevm@1.0.0BhZfgithub.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/chain-capabilities/evm/capability;evmb\x06proto3"

var file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_goTypes = []any{
	(*chain_service.CallContractRequest)(nil),          // 0: loop.chain_capabilities.evm.CallContractRequest
	(*chain_service.FilterLogsRequest)(nil),            // 1: loop.chain_capabilities.evm.FilterLogsRequest
	(*chain_service.BalanceAtRequest)(nil),             // 2: loop.chain_capabilities.evm.BalanceAtRequest
	(*chain_service.EstimateGasRequest)(nil),           // 3: loop.chain_capabilities.evm.EstimateGasRequest
	(*chain_service.GetTransactionByHashRequest)(nil),  // 4: loop.chain_capabilities.evm.GetTransactionByHashRequest
	(*chain_service.GetTransactionReceiptRequest)(nil), // 5: loop.chain_capabilities.evm.GetTransactionReceiptRequest
	(*emptypb.Empty)(nil),                              // 6: google.protobuf.Empty
	(*chain_service.QueryTrackedLogsRequest)(nil),      // 7: loop.chain_capabilities.evm.QueryTrackedLogsRequest
	(*chain_service.RegisterLogTrackingRequest)(nil),   // 8: loop.chain_capabilities.evm.RegisterLogTrackingRequest
	(*chain_service.UnregisterLogTrackingRequest)(nil), // 9: loop.chain_capabilities.evm.UnregisterLogTrackingRequest
	(*chain_service.CallContractReply)(nil),            // 10: loop.chain_capabilities.evm.CallContractReply
	(*chain_service.FilterLogsReply)(nil),              // 11: loop.chain_capabilities.evm.FilterLogsReply
	(*chain_service.BalanceAtReply)(nil),               // 12: loop.chain_capabilities.evm.BalanceAtReply
	(*chain_service.EstimateGasReply)(nil),             // 13: loop.chain_capabilities.evm.EstimateGasReply
	(*chain_service.GetTransactionByHashReply)(nil),    // 14: loop.chain_capabilities.evm.GetTransactionByHashReply
	(*chain_service.GetTransactionReceiptReply)(nil),   // 15: loop.chain_capabilities.evm.GetTransactionReceiptReply
	(*chain_service.LatestAndFinalizedHeadReply)(nil),  // 16: loop.chain_capabilities.evm.LatestAndFinalizedHeadReply
	(*chain_service.QueryTrackedLogsReply)(nil),        // 17: loop.chain_capabilities.evm.QueryTrackedLogsReply
}
var file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_depIdxs = []int32{
	0,  // 0: cre.sdk.v2.evm.Client.CallContract:input_type -> loop.chain_capabilities.evm.CallContractRequest
	1,  // 1: cre.sdk.v2.evm.Client.FilterLogs:input_type -> loop.chain_capabilities.evm.FilterLogsRequest
	2,  // 2: cre.sdk.v2.evm.Client.BalanceAt:input_type -> loop.chain_capabilities.evm.BalanceAtRequest
	3,  // 3: cre.sdk.v2.evm.Client.EstimateGas:input_type -> loop.chain_capabilities.evm.EstimateGasRequest
	4,  // 4: cre.sdk.v2.evm.Client.GetTransactionByHash:input_type -> loop.chain_capabilities.evm.GetTransactionByHashRequest
	5,  // 5: cre.sdk.v2.evm.Client.GetTransactionReceipt:input_type -> loop.chain_capabilities.evm.GetTransactionReceiptRequest
	6,  // 6: cre.sdk.v2.evm.Client.LatestAndFinalizedHead:input_type -> google.protobuf.Empty
	7,  // 7: cre.sdk.v2.evm.Client.QueryTrackedLogs:input_type -> loop.chain_capabilities.evm.QueryTrackedLogsRequest
	8,  // 8: cre.sdk.v2.evm.Client.RegisterLogTracking:input_type -> loop.chain_capabilities.evm.RegisterLogTrackingRequest
	9,  // 9: cre.sdk.v2.evm.Client.UnregisterLogTracking:input_type -> loop.chain_capabilities.evm.UnregisterLogTrackingRequest
	10, // 10: cre.sdk.v2.evm.Client.CallContract:output_type -> loop.chain_capabilities.evm.CallContractReply
	11, // 11: cre.sdk.v2.evm.Client.FilterLogs:output_type -> loop.chain_capabilities.evm.FilterLogsReply
	12, // 12: cre.sdk.v2.evm.Client.BalanceAt:output_type -> loop.chain_capabilities.evm.BalanceAtReply
	13, // 13: cre.sdk.v2.evm.Client.EstimateGas:output_type -> loop.chain_capabilities.evm.EstimateGasReply
	14, // 14: cre.sdk.v2.evm.Client.GetTransactionByHash:output_type -> loop.chain_capabilities.evm.GetTransactionByHashReply
	15, // 15: cre.sdk.v2.evm.Client.GetTransactionReceipt:output_type -> loop.chain_capabilities.evm.GetTransactionReceiptReply
	16, // 16: cre.sdk.v2.evm.Client.LatestAndFinalizedHead:output_type -> loop.chain_capabilities.evm.LatestAndFinalizedHeadReply
	17, // 17: cre.sdk.v2.evm.Client.QueryTrackedLogs:output_type -> loop.chain_capabilities.evm.QueryTrackedLogsReply
	6,  // 18: cre.sdk.v2.evm.Client.RegisterLogTracking:output_type -> google.protobuf.Empty
	6,  // 19: cre.sdk.v2.evm.Client.UnregisterLogTracking:output_type -> google.protobuf.Empty
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_init() }
func file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_init() {
	if File_capabilities_v2_chain_capabilities_evm_capability_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_rawDesc), len(file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_goTypes,
		DependencyIndexes: file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_depIdxs,
	}.Build()
	File_capabilities_v2_chain_capabilities_evm_capability_capability_proto = out.File
	file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_goTypes = nil
	file_capabilities_v2_chain_capabilities_evm_capability_capability_proto_depIdxs = nil
}
