// Code generated by requirements_gen, DO NOT EDIT.

package host

import (
	"context"

	"github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
)

// RequirementsHandler contains a callback for each public field in sdk.Requirements.
// Each callback receives the field value and returns a boolean indicating whether the requirement is satisfied.
type RequirementsHandler struct {
	Tee func(context.Context, *sdk.Tee) bool
}

// CheckRequirements calls each non-nil callback in the handler for the corresponding
// non-nil field in req, returning false if any are false, or if the handler is nil.
// Unknown fields on the proto also result in a false return value.
func CheckRequirements(ctx context.Context, handler RequirementsHandler, req *sdk.Requirements) bool {
	if req == nil {
		return true
	}

	if len(req.ProtoReflect().GetUnknown()) != 0 {
		return false
	}

	if req.Tee != nil {
		if handler.Tee == nil || !handler.Tee(ctx, req.Tee) {
			return false
		}

	}

	return true
}

// HandlesRequirements reports whether handler is the right *type* of runner for req:
// it has a (non-nil) callback for every non-nil field in req, regardless of whether
// those callbacks would be satisfied. It lets callers distinguish a transient
// "a runner of this type exists but cannot currently satisfy the requirements"
// (e.g. a capability that gates the runner is unavailable or not yet activated
// across the DON) from a permanent "no runner of this type is configured at all".
func HandlesRequirements(handler RequirementsHandler, req *sdk.Requirements) bool {
	if req == nil {
		return true
	}

	if len(req.ProtoReflect().GetUnknown()) != 0 {
		return false
	}

	if req.Tee != nil && handler.Tee == nil {
		return false
	}

	return true
}
