// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package server

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc/pkg/test_capabilities/basictrigger"
	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	caperrors "github.com/smartcontractkit/chainlink-common/pkg/capabilities/errors"
	"github.com/smartcontractkit/chainlink-common/pkg/types/core"
)

// Avoid unused imports if there is configuration type
var _ = emptypb.Empty{}

type BasicCapability interface {
	RegisterTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *basictrigger.Config) (<-chan capabilities.TriggerAndId[*basictrigger.Outputs], caperrors.Error)
	UnregisterTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *basictrigger.Config) caperrors.Error
	AckEvent(ctx context.Context, triggerId string, eventId string) caperrors.Error

	Start(ctx context.Context) error
	Close() error
	HealthReport() map[string]error
	Name() string
	Description() string
	Ready() error
	Initialise(ctx context.Context, dependencies core.StandardCapabilitiesDependencies) error
}

func NewBasicServer(capability BasicCapability) *BasicServer {
	stopCh := make(chan struct{})
	return &BasicServer{
		basicCapability: basicCapability{BasicCapability: capability, stopCh: stopCh},
		stopCh:          stopCh,
	}
}

type BasicServer struct {
	basicCapability
	capabilityRegistry core.CapabilitiesRegistry
	stopCh             chan struct{}
}

func (c *BasicServer) Initialise(ctx context.Context, dependencies core.StandardCapabilitiesDependencies) error {
	if err := c.BasicCapability.Initialise(ctx, dependencies); err != nil {
		return fmt.Errorf("error when initializing capability: %w", err)
	}

	c.capabilityRegistry = dependencies.CapabilityRegistry

	if err := dependencies.CapabilityRegistry.Add(ctx, &basicCapability{
		BasicCapability: c.BasicCapability,
	}); err != nil {
		return fmt.Errorf("error when adding %s to the registry: %w", "basic-test-trigger@1.0.0", err)
	}

	return nil
}

func (c *BasicServer) Close() error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	if c.capabilityRegistry != nil {
		if err := c.capabilityRegistry.Remove(ctx, "basic-test-trigger@1.0.0"); err != nil {
			return err
		}
	}

	if c.stopCh != nil {
		close(c.stopCh)
	}

	return c.basicCapability.Close()
}

func (c *BasicServer) Infos(ctx context.Context) ([]capabilities.CapabilityInfo, error) {
	info, err := c.basicCapability.Info(ctx)
	if err != nil {
		return nil, err
	}
	return []capabilities.CapabilityInfo{info}, nil
}

type basicCapability struct {
	BasicCapability
	stopCh chan struct{}
}

func (c *basicCapability) Info(ctx context.Context) (capabilities.CapabilityInfo, error) {
	// Maybe we do need to split it out, even if the user doesn't see it
	return capabilities.NewCapabilityInfo("basic-test-trigger@1.0.0", capabilities.CapabilityTypeCombined, c.BasicCapability.Description())
}

var _ capabilities.ExecutableAndTriggerCapability = (*basicCapability)(nil)

const BasicID = "basic-test-trigger@1.0.0"

func (c *basicCapability) RegisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) (<-chan capabilities.TriggerResponse, error) {
	switch request.Method {
	case "Trigger":
		input := &basictrigger.Config{}
		return capabilities.RegisterTrigger(ctx, c.stopCh, "basic-test-trigger@1.0.0", request, input, c.BasicCapability.RegisterTrigger)
	default:
		return nil, fmt.Errorf("trigger %s not found", request.Method)
	}
}

func (c *basicCapability) UnregisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) error {
	switch request.Method {
	case "Trigger":
		input := &basictrigger.Config{}
		_, err := capabilities.FromValueOrAny(request.Config, request.Payload, input)
		if err != nil {
			return err
		}
		return c.BasicCapability.UnregisterTrigger(ctx, request.TriggerID, request.Metadata, input)
	default:
		return fmt.Errorf("method %s not found", request.Method)
	}
}

func (c *basicCapability) AckEvent(ctx context.Context, triggerId string, eventId string) error {
	return c.BasicCapability.AckEvent(ctx, triggerId, eventId)
}

func (c *basicCapability) RegisterToWorkflow(ctx context.Context, request capabilities.RegisterToWorkflowRequest) error {
	return nil
}

func (c *basicCapability) UnregisterFromWorkflow(ctx context.Context, request capabilities.UnregisterFromWorkflowRequest) error {
	return nil
}

func (c *basicCapability) Execute(ctx context.Context, request capabilities.CapabilityRequest) (capabilities.CapabilityResponse, error) {
	return capabilities.CapabilityResponse{}, fmt.Errorf("method %s not found", request.Method)
}
