// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: import.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdaptedThing  string                 `protobuf:"bytes,1,opt,name=adapted_thing,json=adaptedThing,proto3" json:"adapted_thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outputs) Reset() {
	*x = Outputs{}
	mi := &file_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outputs) ProtoMessage() {}

func (x *Outputs) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outputs.ProtoReflect.Descriptor instead.
func (*Outputs) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

func (x *Outputs) GetAdaptedThing() string {
	if x != nil {
		return x.AdaptedThing
	}
	return ""
}

var File_import_proto protoreflect.FileDescriptor

const file_import_proto_rawDesc = "" +
	"\n" +
	"\fimport.proto\x12\x11importclash.p2.v1\".\n" +
	"\aOutputs\x12#\n" +
	"\radapted_thing\x18\x01 \x01(\tR\fadaptedThingBqZogithub.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc/pkg/test_capabilities/importclash/p2/pbb\x06proto3"

var (
	file_import_proto_rawDescOnce sync.Once
	file_import_proto_rawDescData []byte
)

func file_import_proto_rawDescGZIP() []byte {
	file_import_proto_rawDescOnce.Do(func() {
		file_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)))
	})
	return file_import_proto_rawDescData
}

var file_import_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_import_proto_goTypes = []any{
	(*Outputs)(nil), // 0: importclash.p2.v1.Outputs
}
var file_import_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_import_proto_init() }
func file_import_proto_init() {
	if File_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_import_proto_goTypes,
		DependencyIndexes: file_import_proto_depIdxs,
		MessageInfos:      file_import_proto_msgTypes,
	}.Build()
	File_import_proto = out.File
	file_import_proto_goTypes = nil
	file_import_proto_depIdxs = nil
}
