// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: capabilities/v2/pb/capabilities_v2.proto

package pb

import (
	pb "github.com/smartcontractkit/chainlink-common/pkg/capabilities/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *pb.RequestMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ConfigPayload *anypb.Any             `protobuf:"bytes,2,opt,name=config_payload,json=configPayload,proto3" json:"config_payload,omitempty"`
	InputPayload  *anypb.Any             `protobuf:"bytes,3,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityRequest) GetMetadata() *pb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CapabilityRequest) GetConfigPayload() *anypb.Any {
	if x != nil {
		return x.ConfigPayload
	}
	return nil
}

func (x *CapabilityRequest) GetInputPayload() *anypb.Any {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

type CapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputPayload *anypb.Any             `protobuf:"bytes,1,opt,name=output_payload,json=outputPayload,proto3" json:"output_payload,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      *pb.ResponseMetadata   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityResponse) Reset() {
	*x = CapabilityResponse{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResponse) ProtoMessage() {}

func (x *CapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResponse.ProtoReflect.Descriptor instead.
func (*CapabilityResponse) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityResponse) GetOutputPayload() *anypb.Any {
	if x != nil {
		return x.OutputPayload
	}
	return nil
}

func (x *CapabilityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CapabilityResponse) GetMetadata() *pb.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TriggerRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Metadata       *pb.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload        *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerRegistrationRequest) Reset() {
	*x = TriggerRegistrationRequest{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRegistrationRequest) ProtoMessage() {}

func (x *TriggerRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRegistrationRequest.ProtoReflect.Descriptor instead.
func (*TriggerRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *TriggerRegistrationRequest) GetMetadata() *pb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TriggerRegistrationRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TriggerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerType   string                 `protobuf:"bytes,1,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	TriggerId     string                 `protobuf:"bytes,2,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEvent) Reset() {
	*x = TriggerEvent{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEvent) ProtoMessage() {}

func (x *TriggerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEvent.ProtoReflect.Descriptor instead.
func (*TriggerEvent) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerEvent) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *TriggerEvent) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *TriggerEvent) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *TriggerEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerResponse) GetEvent() *TriggerEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TriggerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TriggerResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TriggerResponseMessage_Ack
	//	*TriggerResponseMessage_Response
	Message       isTriggerResponseMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponseMessage) Reset() {
	*x = TriggerResponseMessage{}
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponseMessage) ProtoMessage() {}

func (x *TriggerResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponseMessage.ProtoReflect.Descriptor instead.
func (*TriggerResponseMessage) Descriptor() ([]byte, []int) {
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerResponseMessage) GetMessage() isTriggerResponseMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TriggerResponseMessage) GetAck() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Message.(*TriggerResponseMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *TriggerResponseMessage) GetResponse() *TriggerResponse {
	if x != nil {
		if x, ok := x.Message.(*TriggerResponseMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isTriggerResponseMessage_Message interface {
	isTriggerResponseMessage_Message()
}

type TriggerResponseMessage_Ack struct {
	Ack *emptypb.Empty `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type TriggerResponseMessage_Response struct {
	Response *TriggerResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*TriggerResponseMessage_Ack) isTriggerResponseMessage_Message() {}

func (*TriggerResponseMessage_Response) isTriggerResponseMessage_Message() {}

var File_capabilities_v2_pb_capabilities_v2_proto protoreflect.FileDescriptor

const file_capabilities_v2_pb_capabilities_v2_proto_rawDesc = "" +
	"\n" +
	"(capabilities/v2/pb/capabilities_v2.proto\x12\x0fcapabilities_v2\x1a\"capabilities/pb/capabilities.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x01\n" +
	"\x11CapabilityRequest\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.capabilities.RequestMetadataR\bmetadata\x12;\n" +
	"\x0econfig_payload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\rconfigPayload\x129\n" +
	"\rinput_payload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\finputPayload\"\xa3\x01\n" +
	"\x12CapabilityResponse\x12;\n" +
	"\x0eoutput_payload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\routputPayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1e.capabilities.ResponseMetadataR\bmetadata\"\xb0\x01\n" +
	"\x1aTriggerRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.capabilities.RequestMetadataR\bmetadata\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x80\x01\n" +
	"\fTriggerEvent\x12!\n" +
	"\ftrigger_type\x18\x01 \x01(\tR\vtriggerType\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x02 \x01(\tR\ttriggerId\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\\\n" +
	"\x0fTriggerResponse\x123\n" +
	"\x05event\x18\x01 \x01(\v2\x1d.capabilities_v2.TriggerEventR\x05event\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8f\x01\n" +
	"\x16TriggerResponseMessage\x12*\n" +
	"\x03ack\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03ack\x12>\n" +
	"\bresponse\x18\x02 \x01(\v2 .capabilities_v2.TriggerResponseH\x00R\bresponseB\t\n" +
	"\amessage2\xf2\x02\n" +
	"\n" +
	"Capability\x12C\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a!.capabilities.CapabilityInfoReply\"\x00\x12V\n" +
	"\aExecute\x12\".capabilities_v2.CapabilityRequest\x1a#.capabilities_v2.CapabilityResponse\"\x000\x01\x12k\n" +
	"\x0fRegisterTrigger\x12+.capabilities_v2.TriggerRegistrationRequest\x1a'.capabilities_v2.TriggerResponseMessage\"\x000\x01\x12Z\n" +
	"\x11UnregisterTrigger\x12+.capabilities_v2.TriggerRegistrationRequest\x1a\x16.google.protobuf.Empty\"\x00BEZCgithub.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/pbb\x06proto3"

var (
	file_capabilities_v2_pb_capabilities_v2_proto_rawDescOnce sync.Once
	file_capabilities_v2_pb_capabilities_v2_proto_rawDescData []byte
)

func file_capabilities_v2_pb_capabilities_v2_proto_rawDescGZIP() []byte {
	file_capabilities_v2_pb_capabilities_v2_proto_rawDescOnce.Do(func() {
		file_capabilities_v2_pb_capabilities_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capabilities_v2_pb_capabilities_v2_proto_rawDesc), len(file_capabilities_v2_pb_capabilities_v2_proto_rawDesc)))
	})
	return file_capabilities_v2_pb_capabilities_v2_proto_rawDescData
}

var file_capabilities_v2_pb_capabilities_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_capabilities_v2_pb_capabilities_v2_proto_goTypes = []any{
	(*CapabilityRequest)(nil),          // 0: capabilities_v2.CapabilityRequest
	(*CapabilityResponse)(nil),         // 1: capabilities_v2.CapabilityResponse
	(*TriggerRegistrationRequest)(nil), // 2: capabilities_v2.TriggerRegistrationRequest
	(*TriggerEvent)(nil),               // 3: capabilities_v2.TriggerEvent
	(*TriggerResponse)(nil),            // 4: capabilities_v2.TriggerResponse
	(*TriggerResponseMessage)(nil),     // 5: capabilities_v2.TriggerResponseMessage
	(*pb.RequestMetadata)(nil),         // 6: capabilities.RequestMetadata
	(*anypb.Any)(nil),                  // 7: google.protobuf.Any
	(*pb.ResponseMetadata)(nil),        // 8: capabilities.ResponseMetadata
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
	(*pb.CapabilityInfoReply)(nil),     // 10: capabilities.CapabilityInfoReply
}
var file_capabilities_v2_pb_capabilities_v2_proto_depIdxs = []int32{
	6,  // 0: capabilities_v2.CapabilityRequest.metadata:type_name -> capabilities.RequestMetadata
	7,  // 1: capabilities_v2.CapabilityRequest.config_payload:type_name -> google.protobuf.Any
	7,  // 2: capabilities_v2.CapabilityRequest.input_payload:type_name -> google.protobuf.Any
	7,  // 3: capabilities_v2.CapabilityResponse.output_payload:type_name -> google.protobuf.Any
	8,  // 4: capabilities_v2.CapabilityResponse.metadata:type_name -> capabilities.ResponseMetadata
	6,  // 5: capabilities_v2.TriggerRegistrationRequest.metadata:type_name -> capabilities.RequestMetadata
	7,  // 6: capabilities_v2.TriggerRegistrationRequest.payload:type_name -> google.protobuf.Any
	7,  // 7: capabilities_v2.TriggerEvent.payload:type_name -> google.protobuf.Any
	3,  // 8: capabilities_v2.TriggerResponse.event:type_name -> capabilities_v2.TriggerEvent
	9,  // 9: capabilities_v2.TriggerResponseMessage.ack:type_name -> google.protobuf.Empty
	4,  // 10: capabilities_v2.TriggerResponseMessage.response:type_name -> capabilities_v2.TriggerResponse
	9,  // 11: capabilities_v2.Capability.Info:input_type -> google.protobuf.Empty
	0,  // 12: capabilities_v2.Capability.Execute:input_type -> capabilities_v2.CapabilityRequest
	2,  // 13: capabilities_v2.Capability.RegisterTrigger:input_type -> capabilities_v2.TriggerRegistrationRequest
	2,  // 14: capabilities_v2.Capability.UnregisterTrigger:input_type -> capabilities_v2.TriggerRegistrationRequest
	10, // 15: capabilities_v2.Capability.Info:output_type -> capabilities.CapabilityInfoReply
	1,  // 16: capabilities_v2.Capability.Execute:output_type -> capabilities_v2.CapabilityResponse
	5,  // 17: capabilities_v2.Capability.RegisterTrigger:output_type -> capabilities_v2.TriggerResponseMessage
	9,  // 18: capabilities_v2.Capability.UnregisterTrigger:output_type -> google.protobuf.Empty
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_capabilities_v2_pb_capabilities_v2_proto_init() }
func file_capabilities_v2_pb_capabilities_v2_proto_init() {
	if File_capabilities_v2_pb_capabilities_v2_proto != nil {
		return
	}
	file_capabilities_v2_pb_capabilities_v2_proto_msgTypes[5].OneofWrappers = []any{
		(*TriggerResponseMessage_Ack)(nil),
		(*TriggerResponseMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_v2_pb_capabilities_v2_proto_rawDesc), len(file_capabilities_v2_pb_capabilities_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capabilities_v2_pb_capabilities_v2_proto_goTypes,
		DependencyIndexes: file_capabilities_v2_pb_capabilities_v2_proto_depIdxs,
		MessageInfos:      file_capabilities_v2_pb_capabilities_v2_proto_msgTypes,
	}.Build()
	File_capabilities_v2_pb_capabilities_v2_proto = out.File
	file_capabilities_v2_pb_capabilities_v2_proto_goTypes = nil
	file_capabilities_v2_pb_capabilities_v2_proto_depIdxs = nil
}
