package configdoc

import (
	"strings"
	"testing"

	"github.com/smartcontractkit/chainlink-common/pkg/config"
	"github.com/stretchr/testify/require"
)

func TestDefaultsOnly(t *testing.T) {
	t.Run("basic test", func(t *testing.T) {
		type keys struct {
			Key *string
		}
		type nested struct {
			Test  *string
			Count *int
		}
		type cfg struct {
			Foo    *bool
			Bar    *int
			Nested nested
			Keys   []keys
			Extra  []keys
			Chains map[string]*nested
		}

		def := `# Code generated by gen. DO NOT EDIT.

# Foo is a boolean field.
Foo = false # Default
# Bar is a number.
Bar = 42 # Example
[Nested]
  # Test holds a string.
  Test = "test" # Example
  # Count is a number.
  Count = 7 # Default
  [[Nested.Keys]] # Example
    # Key is the API key.
    Key = "abc" # Example

# Extra is an unmarked array of tables.
[[Extra]]
  # Key is the API key.
  Key = "def" # Default

# Chains maps a selector to its settings.
[Chains.1]
  # Count is a number.
  Count = 9 # Default

`

		var c cfg
		require.NoError(t, DefaultsOnly(strings.NewReader(def), &c, config.DecodeTOML))

		require.False(t, *c.Foo)
		require.Zero(t, *c.Bar, "examples decode as zero values")
		require.Equal(t, 7, *c.Nested.Count)
		require.Zero(t, *c.Nested.Test, "indented examples decode as zero values")
		require.Empty(t, c.Keys, "arrays of tables are ignored")
		require.Empty(t, c.Extra, "unmarked arrays of tables are ignored too")
		require.Equal(t, 9, *c.Chains["1"].Count)
		require.Zero(t, *c.Chains["1"].Test, "map entries are descended into")
	})

	t.Run("array of tables", func(t *testing.T) {
		type keys struct {
			Key *string
		}
		type nested struct {
			Test  *string
			Count *int
		}
		type cfg struct {
			Foo    *bool
			Extra  []keys
			Nested nested
			Chains map[string]*nested
		}

		t.Run("followed by a table with no blank line", func(t *testing.T) {
			def := `[[Extra]]
  # Key is the API key.
  Key = "def" # Default
[Nested]
  # Count is a number.
  Count = 7 # Default
  [[Nested.Keys]] # Example
    # Key is the API key.
    Key = "abc" # Default
[Chains.1]
  # Count is a number.
  Count = 9 # Default
`

			var c cfg
			require.NoError(t, DefaultsOnly(strings.NewReader(def), &c, config.DecodeTOML))

			require.Empty(t, c.Extra, "arrays of tables are ignored")
			require.Equal(t, 7, *c.Nested.Count, "tables after an array of tables are kept")
			require.Equal(t, 9, *c.Chains["1"].Count, "tables after a nested array of tables are kept")
		})

		t.Run("with a blank line before its own keys", func(t *testing.T) {
			def := `# Foo is a boolean field.
Foo = true # Default
[[Extra]]
  # Key is the API key.
  Key = "def" # Default

  # Key is still part of Extra.
  Key = "ghi" # Default
[Nested]
  # Count is a number.
  Count = 7 # Default
`

			var c cfg
			require.NoError(t, DefaultsOnly(strings.NewReader(def), &c, config.DecodeTOML))

			require.True(t, *c.Foo)
			require.Empty(t, c.Extra, "keys after a blank line still belong to the array of tables")
			require.Equal(t, 7, *c.Nested.Count)
		})

		t.Run("marked as an example", func(t *testing.T) {
			def := `[[Extra]] # Example
  # Key is the API key.
  Key = "def" # Default
[Nested]
  # Count is a number.
  Count = 7 # Default
`

			var c cfg
			require.NoError(t, DefaultsOnly(strings.NewReader(def), &c, config.DecodeTOML))

			require.Empty(t, c.Extra, "defaults under an example array of tables are ignored")
			require.Equal(t, 7, *c.Nested.Count)
		})
	})
}
