WorkflowLimit = '1000'
WorkflowExecutionConcurrencyLimit = '1000'
GatewayIncomingPayloadSizeLimit = '1mb'
GatewayVaultManagementEnabled = 'true'
VaultJWTAuthEnabled = 'false'
VaultOrgIdAsSecretOwnerEnabled = 'false'
VaultForceEmptyOCRRounds = 'false'
GatewayHTTPGlobalRate = '500rps:500'
GatewayHTTPPerNodeRate = '100rps:100'
GatewayConfidentialRelayGlobalRate = '50rps:10'
GatewayConfidentialRelayPerNodeRate = '10rps:10'
TriggerRegistrationStatusUpdateTimeout = '0s'
BaseTriggerRetransmitEnabled = 'false'
BaseTriggerRetryInterval = '30s'
VaultCiphertextSizeLimit = '2kb'
VaultShareSizeLimit = '600b'
VaultIdentifierKeySizeLimit = '64b'
VaultIdentifierOwnerSizeLimit = '64b'
VaultIdentifierNamespaceSizeLimit = '64b'
VaultPluginBatchSizeLimit = '10'
VaultRequestBatchSizeLimit = '10'
VaultMaxQuerySizeLimit = '102.4kb'
VaultMaxObservationSizeLimit = '512kb'
VaultMaxReportsPlusPrecursorSizeLimit = '2mb'
VaultMaxReportSizeLimit = '2mb'
VaultMaxReportCount = '10'
VaultMaxKeyValueModifiedKeysPlusValuesSizeLimit = '1.468006mb'
VaultMaxKeyValueModifiedKeys = '300'
VaultMaxBlobPayloadSizeLimit = '25.6kb'
VaultMaxPerOracleUnexpiredBlobCumulativePayloadSizeLimit = '31.45728mb'
VaultMaxPerOracleUnexpiredBlobCount = '1000'

[PerOrg]
WorkflowExecutionConcurrencyLimit = '100'
ZeroBalancePruningTimeout = '24h0m0s'

[PerOwner]
WorkflowLimit = '1000'
WorkflowExecutionConcurrencyLimit = '5'
VaultSecretsLimit = '100'

[PerWorkflow]
TriggerRegistrationsTimeout = '10s'
TriggerSubscriptionTimeout = '15s'
TriggerSubscriptionLimit = '10'
TriggerEventQueueLimit = '50'
TriggerEventQueueTimeout = '10m0s'
CapabilityConcurrencyLimit = '30'
CapabilityCallTimeout = '3m0s'
SecretsConcurrencyLimit = '5'
ExecutionConcurrencyLimit = '5'
ExecutionTimeout = '5m0s'
ExecutionResponseLimit = '100kb'
ExecutionTimestampsEnabled = 'false'
WASMMemoryLimit = '100mb'
WASMBinarySizeLimit = '100mb'
WASMCompressedBinarySizeLimit = '20mb'
WASMConfigSizeLimit = '1mb'
WASMSecretsSizeLimit = '1mb'
LogLineLimit = '1kb'
LogEventLimit = '1000'
UserMetricEnabled = 'false'
UserMetricPayloadLimit = '4kb'
UserMetricNameLengthLimit = '128'
UserMetricLabelsPerMetric = '10'
UserMetricLabelValueLength = '256'
FeatureMultiTriggerExecutionIDsActiveAt = '2100-01-01 00:00:00 +0000 UTC'
FeatureMultiTriggerExecutionIDsActivePeriod = '[2100-01-01 00:00:00 +0000 UTC,2101-01-01 00:00:00 +0000 UTC]'
FeatureChainCapabilityHashBasedOCRActivePeriod = '[2100-01-01 00:00:00 +0000 UTC,2101-01-01 00:00:00 +0000 UTC]'

[PerWorkflow.ChainAllowed]
Default = 'false'

[PerWorkflow.ChainAllowed.Values]
12463857294658392847 = 'true'
12922642891491394802 = 'true'
3379446385462418246 = 'true'

[PerWorkflow.CRONTrigger]
FastestScheduleInterval = '30s'

[PerWorkflow.HTTPTrigger]
RateLimit = 'every30s:3'

[PerWorkflow.LogTrigger]
EventRateLimit = 'every6s:10'
EventSizeLimit = '5kb'
FilterAddressLimit = '5'
FilterTopicsPerSlotLimit = '10'

[PerWorkflow.ChainWrite]
TargetsLimit = '10'
ReportSizeLimit = '5kb'

[PerWorkflow.ChainWrite.EVM]
TransactionGasLimit = '5000000'
ReportSizeLimit = '5kb'

[PerWorkflow.ChainWrite.EVM.GasLimit]
Default = '5000000'

[PerWorkflow.ChainWrite.EVM.GasLimit.Values]
12922642891491394802 = '50000000'
3379446385462418246 = '10000000'

[PerWorkflow.ChainWrite.Solana]
ReportSizeLimit = '265b'

[PerWorkflow.ChainWrite.Solana.GasLimit]
Default = '300000'

[PerWorkflow.ChainWrite.Solana.GasLimit.Values]

[PerWorkflow.ChainWrite.Aptos]
ReportSizeLimit = '5kb'

[PerWorkflow.ChainWrite.Aptos.GasLimit]
Default = '2000000'

[PerWorkflow.ChainWrite.Aptos.GasLimit.Values]

[PerWorkflow.ChainRead]
CallLimit = '15'
LogQueryBlockLimit = '100'
PayloadSizeLimit = '5kb'

[PerWorkflow.Consensus]
ObservationSizeLimit = '100kb'
CallLimit = '20'

[PerWorkflow.HTTPAction]
CallLimit = '5'
CacheAgeLimit = '10m0s'
ConnectionTimeout = '10s'
RequestSizeLimit = '10kb'
ResponseSizeLimit = '100kb'

[PerWorkflow.ConfidentialHTTP]
CallLimit = '5'
ConnectionTimeout = '10s'
RequestSizeLimit = '10kb'
ResponseSizeLimit = '100kb'

[PerWorkflow.Secrets]
CallLimit = '5'
