// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: msghasher.proto

package ccipocr3pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashMsgInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *Message               `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashMsgInput) Reset() {
	*x = HashMsgInput{}
	mi := &file_msghasher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMsgInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMsgInput) ProtoMessage() {}

func (x *HashMsgInput) ProtoReflect() protoreflect.Message {
	mi := &file_msghasher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMsgInput.ProtoReflect.Descriptor instead.
func (*HashMsgInput) Descriptor() ([]byte, []int) {
	return file_msghasher_proto_rawDescGZIP(), []int{0}
}

func (x *HashMsgInput) GetMsg() *Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

type HashMsgOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashMsgOutput) Reset() {
	*x = HashMsgOutput{}
	mi := &file_msghasher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMsgOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMsgOutput) ProtoMessage() {}

func (x *HashMsgOutput) ProtoReflect() protoreflect.Message {
	mi := &file_msghasher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMsgOutput.ProtoReflect.Descriptor instead.
func (*HashMsgOutput) Descriptor() ([]byte, []int) {
	return file_msghasher_proto_rawDescGZIP(), []int{1}
}

func (x *HashMsgOutput) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_msghasher_proto protoreflect.FileDescriptor

const file_msghasher_proto_rawDesc = "" +
	"\n" +
	"\x0fmsghasher.proto\x12\x19loop.internal.pb.ccipocr3\x1a\fmodels.proto\"D\n" +
	"\fHashMsgInput\x124\n" +
	"\x03msg\x18\x01 \x01(\v2\".loop.internal.pb.ccipocr3.MessageR\x03msg\"#\n" +
	"\rHashMsgOutput\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash2i\n" +
	"\tMsgHasher\x12\\\n" +
	"\aHashMsg\x12'.loop.internal.pb.ccipocr3.HashMsgInput\x1a(.loop.internal.pb.ccipocr3.HashMsgOutputBWZUgithub.com/smartcontractkit/chainlink-common/pkg/loop/internal/pb/ccipocr3;ccipocr3pbb\x06proto3"

var (
	file_msghasher_proto_rawDescOnce sync.Once
	file_msghasher_proto_rawDescData []byte
)

func file_msghasher_proto_rawDescGZIP() []byte {
	file_msghasher_proto_rawDescOnce.Do(func() {
		file_msghasher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msghasher_proto_rawDesc), len(file_msghasher_proto_rawDesc)))
	})
	return file_msghasher_proto_rawDescData
}

var file_msghasher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msghasher_proto_goTypes = []any{
	(*HashMsgInput)(nil),  // 0: loop.internal.pb.ccipocr3.HashMsgInput
	(*HashMsgOutput)(nil), // 1: loop.internal.pb.ccipocr3.HashMsgOutput
	(*Message)(nil),       // 2: loop.internal.pb.ccipocr3.Message
}
var file_msghasher_proto_depIdxs = []int32{
	2, // 0: loop.internal.pb.ccipocr3.HashMsgInput.msg:type_name -> loop.internal.pb.ccipocr3.Message
	0, // 1: loop.internal.pb.ccipocr3.MsgHasher.HashMsg:input_type -> loop.internal.pb.ccipocr3.HashMsgInput
	1, // 2: loop.internal.pb.ccipocr3.MsgHasher.HashMsg:output_type -> loop.internal.pb.ccipocr3.HashMsgOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msghasher_proto_init() }
func file_msghasher_proto_init() {
	if File_msghasher_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msghasher_proto_rawDesc), len(file_msghasher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msghasher_proto_goTypes,
		DependencyIndexes: file_msghasher_proto_depIdxs,
		MessageInfos:      file_msghasher_proto_msgTypes,
	}.Build()
	File_msghasher_proto = out.File
	file_msghasher_proto_goTypes = nil
	file_msghasher_proto_depIdxs = nil
}
