# Builds external repositories that use this so we can create tickets to update them before their ci pipelines break.
# NOTE: This is not a required check to merge, merely a check so you know to create tickets to update the products that rely on this.
name: Build External Repositories
on:
  pull_request:

# Only run 1 of this workflow at a time per PR
concurrency:
  group: integration-build-check-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      core-ref: ${{ steps.set-git-refs.outputs.core-ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Get refs from PR body
        id: set-git-refs
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/get-refs-from-pr-body.js')
            await script({ github, context, core })

  build-chainlink:
    needs: init
    environment:
      name: integration
      deployment: false
    permissions:
      contents: read
      id-token: write
    name: Build Chainlink
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the chainlink-common repo
        uses: actions/checkout@v4
        with:
          repository: smartcontractkit/chainlink-common
          persist-credentials: false
          path: chainlink-common

      - name: Checkout the chainlink core repo
        uses: actions/checkout@v4
        with:
          repository: smartcontractkit/chainlink
          ref: ${{ needs.init.outputs.core-ref }}
          persist-credentials: false
          path: chainlink

      - name: Setup Go
        uses: ./chainlink-common/.github/actions/setup-go
        with:
          go-version-file: "chainlink/go.mod"
          only-modules: "true"

      - name: Build /chainlink
        shell: bash
        env:
          COMMON_SHA: ${{ github.event.pull_request.head.sha }}
        working-directory: chainlink
        run: |
          go get "github.com/smartcontractkit/chainlink-common@${COMMON_SHA}"
          go mod tidy
          make install-chainlink
