name: Observability Lib Checks

on:
  push:
    paths:
      - "observability-lib/**"
      - ".github/**"

permissions:
  contents: read

jobs:
  run-tests:
    # pkg.yml checks observability-lib on pushes to main, so this workflow checks only pushes to
    # other branches.
    if: github.ref_name != 'main'
    defaults:
      run:
        working-directory: observability-lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"

      - name: Build
        run: make build

      - name: Unit Tests
        run: make test
