name: x/config Checks
permissions:
  contents: read

on: [push, merge_group, pull_request]

jobs:
  changes:
    name: detect changes
    runs-on: ubuntu-latest
    outputs:
      x-config-src: ${{ steps.x-config-changes.outputs.src }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: x-config-changes
        with:
          filters: |
            src:
            - 'x/config/**'
            - '.github/workflows/x-config.yml'

  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.x-config-src == 'true'
    defaults:
      run:
        working-directory: x/config
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: ./.github/actions/setup-go
        with:
          go-version-file: "go.mod"
          restore-build-cache-only: "false"

      - name: Build
        run: go build -v ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Unit Tests
        id: run-tests
        continue-on-error: true
        run: gotestsum --format standard-quiet --junitfile test-results.xml -- ./...

      - name: Analyze and upload test results
        uses: smartcontractkit/.github/actions/branch-out-upload@branch-out-upload/v1
        with:
          junit-file-path: x/config/test-results.xml
          trunk-org-slug: chainlink
          trunk-previous-step-outcome: ${{ steps.run-tests.outcome }}
          trunk-token: ${{ secrets.TRUNK_API_KEY }}
          trunk-job-url: ${{ format('https://github.com/{0}/actions/runs/{1}/job/{2}/attempts/{3}', github.repository, github.run_id, job.check_run_id, github.run_attempt) }}

  gate:
    name: summary gate
    runs-on: ubuntu-latest
    needs: [changes, run-tests]
    if: always()
    steps:
      - name: Fail if any job ran and failed
        if: needs.changes.outputs.x-config-src == 'true' && needs.run-tests.result != 'success'
        run: exit 1
